apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-sqlite-pvc
  labels:
    app: api
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-static
  resources:
    requests:
      storage: 10Gi
  # This volume is manually administered in the longhorn UI (including a persistent volume called api-sqlite-static-pv)
  volumeName: api-sqlite-static-pv
