---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: sms-api-rke
spec:
  encryptedData:
    .dockerconfigjson: AgAyw144JmEPGyVzZLl5ZmUQgoVbVWTxKYqvYnm/W1NU5UbeSsO2lotvaGIigQJhZP18LVe2xpXwAYQLbFUgo1CRVo+vlg3iWdU3wfxZlRQ3u8YzjgeWBd7DPaP3jQx9sG1hmb4BTHQqAygRJhjmu9o7Usuih0HfnXOfsvw11IJGaE9GW2iTjC6dVtjIhe1AmPgYTiI2tzU9PsYeK5KFZznGf/KM2/gFMcPoFvc56zlAbPn4Xa4F/LhVXJC1tLseBOtL4AlfbPFbqdwy0j2sC877FLr8xwAiQ8vMqIT3P6hLDbgq/qxNF8Dp9l3TpsIAI5DH+QWysb53d4cHvO449vHE1gRYw5vNrsGzo+k0x/GV777S2RViykTYIK6niUngdiu/DAE6uibdDn2FLiRL8aAPtH+PF9ukonKVhDK2U1emM2pVrwB1bLE2L8Ll1kPcd6prmEsXR9tF9YYgLmHHSO4e2DjYQRr2pxp/PUp1yYmaomuBqXNs+kBfG+OSUQkEIgDpbS5B3/eqEBEpHYkZVm1bLB+jKW/+kfA+aTrBh3zk8fOHc4goht71vRVZmHI3B+B0g5fVVoVMNSpJpjdPSmHcP0UhG7fCZc87dj1eFF87h9WwsZFD0u2YKfpPx1bJ4eG8B/w//YpRy6Gr5cBEec5pv2gJfGVWEw65JgrZPRVbnGIHKhmxPYCexqM6llCDPYcQhZVd7IFCK5jn168Em/pNV63MacSHqCnM4f9rDbtL1IL3QQ+96kThn8Bb77va2swtlY4uvascwIuxp2PGGYue5OjwxFJWQxNuqVOgG83v1619CpwYpjD7sYxoBvm1u2S7upx5kiyGGETgB5Vjk4C69E7YSl6618UDywjDH7hiE3iPUeir+IY3QUOYxI+N/nW30B7JD1lGiCj2Tg5vzp6xUodWHW0KKVVmWSB37Nz8RTRz1vpMh+gUWKCmGyV0Sy5vt6IZOgPdJIjKDlRLdD6WkFKy7nrXnw==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: sms-api-rke
    type: kubernetes.io/dockerconfigjson
