---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: sms-api-rke
spec:
  encryptedData:
    .dockerconfigjson: AgDJN1g6tYACi1mJ6ApdrLLrtUtf+cEi7hGUfoQv+fVWFqC7Vm6hU/IHJ586ItMTicoqLWaOIwc+EuE1wMUHVFUYFk43HV847py8OZOplwgrD0hy7yBQoPqKpavtb/KA/315ccUtXmKKl6Uo0AMQ1tpMRTNDAW9OyidO0M7rsTCd5lC1FuFkr2coIDtXEkaZBgSav8YvjThBa8170TD9vzph3T19wqI70nufzWWqD1+TR7Q/h0wZ8Frb9er+puLpm48EiguWy8ilvks4rvk3HIu7BamJYSIShrKKr3pNhF+FKEiDDn4zP6dgieB8EZPAl6I7q3nlJ4t5HQTtpTKiHn7ccUMB/K4UgiLH1c4EkPUpmWgckdm+dGQM+fOPeKbGuRfKUPuI7yGo8cEQKkEqMjlmWTR9zDB7pienNH71SHT+rloZr05IMG0JyPjQsa5FMVBFRCowYODn1Osn2CkIBYBfZ26pCo/WyE6MziErfSj2rvpXuqsx+JWOvPiZgz9ISg/LUh5jAT8eZCiPsjDk38NNFngvEjl6SqyFMoVgRrNARPdhe0fqc1x1rRdQNMgzNPgBaP8rCsJMg7YZrF8mwEzVoEAxoOSNzhvCxFt2kvQducax+u5UySMIS8bCzdiQyKeods0Lrn1UYHVN8wx9ZAWpYbYBRrGlT/IgYt4hfksaWS6HIhgcTslUExGNzWwWeJG4cItLD1ScZKQ7Mq7OLSaU/7JOxKstwTJXon7IlgMFSPk4w1aeAU6FCJq0XMhRq+PR1zJSbcKGceqIq1DgptZIqkkvgxTlB3+HElEcn0ptbHVAjIrP0mLNcp1KunjY2mISm6XfSm1vzLckjllhaLM4/TQ2odofWomgiNvtPIQDTxN/eiwPQ7X0ycjMs4XcJQSjyyuTwoYYnaecPe1zABhYgLD0ynud4Wgma1GH+KKbNlIaMTvTRMev6+B6dfJ/uQYNS/3pTQuon4XnOPyxKQ3B+ZbA6snEwA==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: sms-api-rke
    type: kubernetes.io/dockerconfigjson
