---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: sms-api-rke
spec:
  encryptedData:
    .dockerconfigjson: AgCmLP3f79AdUcxFYSW3lgBrNDWyWi4Vhhq5P9krvgWDxs/6ncVyNHlMwgQ7Svpm+hoTr/bordVuk2tN1MPpa9gs0habSq3Re+K4v4d+ORjAtZJRhhF2D06mqXOSvu9JpjJBaSx64NO2WGGKZBn4rQxxEXbbkEMd//GfmXFxfTK3XkWjv63IWc387oj/R04nNYQbmbLAu4s7jraxd79yf3ODIymmwEcwhtg+rnT9umtvBQ6TalTvXE5bZ15nlzMzDZzuIbMnlBO7MSGN1Y9c1dnwTkTWqL/+snb8YX6+tjA1QJ3W7H9/wAXP+TAdX6x2ewGRA13WCYugxlEZrcoLybqIGDJNNvB2iCnTCymj0XGV98qU/dZ8yYyc9ydpLmhUuGOEzikBPX6Cv/iQSMQXL9pfPAN359mfVhY1hLPxnuaxtnuUzarSlZOByfzSOFyiu/088FocrgCtpzy8AgB7itvHmQNmR97QCsbdv//bKoRKsOv1sf0utkI73S8RMDfMvOl7SfzbJYDUQNdz/JLQFx0A9UyCxlgq2Qt/DpolFPGySz6nH+SS4IwTpEvJm34T352CfrTxF/MSYvs1HaKK8N5sUVHSR55QPiBSLdYUW9AlA5SiNu/9BEeieEAnAgWTQ7j4EqzvwMXkRZqiTaUDGcEHh583giI4Hrbwvfwfwl8ccZ4ls6f2s57Mz04KD/zvg4zBXckHXt7341bzKJaB8zjFKM19HLnpusvMas1EGCwRXIel3T+++AcQ029jYI0acwr2mrRbG2K2hiu6enrFPQcS3ozPCkbXfexyBYuJ68Cos/T/PvyUVw74N95bUc7SnIyM/vWRQmmbEXEpd8tCU1JVvsckGXbQjQZH9owRh/tbfbyFB3RPmWTRixdDua+xi88cueUx+m8QJozT7JGTdn5FUqShYS2L/MXqVhSCLalVCufExi7z+R0orvl5P0NwFiJHcxg0WDAp+ZY1WSLj/LPh
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: sms-api-rke
    type: kubernetes.io/dockerconfigjson
