---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: sms-api-rke
spec:
  encryptedData:
    .dockerconfigjson: AgBVWdjnKGbExTNmni3b3vBqqNRF3D71aPPGmiHxdtFGutKjdlf0wuntMj8Z1i+tADQceXqen+nJhWpyNanhoMSxzW9BK+huZj/zsQQCGn7Wr+Zmbicry+4OD+915tZClfonQg3/g634dw4cnf9i//iHXu8UKvc8PJzeGG+mefOavUandNdCOugf6ozSZI9zx73etfp0vAQk495I8eLBjbm7oOnW1pErRej53dE5FIuPtpUPAzeYhK5PePKCggO5tCUqb8gCd6CSJVHGM95cWC76rU+ImGOSxuXGN8kfm5C5d9tLBcyo7eVJGfo9eSWOvAZ5A05spp7KK63GrpsGtkCjZUiEPGU9pID6DSPiqyoGFTum4k2Q18lqW9+PLKuUslPnTRszdpDELm2Z8pCqgL5xlvIUR7cggTi9Z2IL/GCcgJ1vWsf216Haa2pH6l7QPIh1pna0NeZz8DrrThozTEvyw3G6i/kC0/lzO8XzNSOiBAC3SENYX7yB5P1FTwYlYaQuhlNtP17XztswamYOwtXfDgiMJybVe6TGJN03y2agykRnVRUHmC8ugvcf99u+oDcG+NQq19mk5mb+3Gvdxq5S1P6LgQc1WFmyUCDsKavMuSORuesgpzH4Z8VCtAQX5/bNL4pE6nlMAoocY6OLgJySoQp4lPBdNA2VNHqZvhx3U8gA3paDf2H2KHSNGOAUZm4/02jlP6rHGhGE9IGnyErsfz0tGRC2QRV6VnbRBqR4xddTXkiNDyRW1WFM3GnsIkeTkMNezWE5+vOuGTdAHf/PcrBwB6QEoAzo4enV32K1y4noSHzIcGbwd2s0oal0nko1D3bd4NIzsKyVfe9mktah2H/sgssTfZR/yiQyb6C1Uonej39iPOAK5sUCNPKvY8n39U9gtWS8PBGCq0w33CZxe2celfQsWyl+NoqPGjPYZUcdE4pljT13lsM7l+vbfq7N84Y5nf3vH9ycsDgSrN6l7Q3JV/Sh+w==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: sms-api-rke
    type: kubernetes.io/dockerconfigjson
