---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: sms-api-rke
spec:
  encryptedData:
    .dockerconfigjson: AgCy2NzVB/UbaULpbjxI0CDJPzw68ubnsyCOyAGO6k0asNb58038aSGhEVuy188kjCP+GQpeE86soLNYF/pXh3zEpE65ojAMfV3oWGHRy45tS1kwTWKAN52DDdpsXFP3RI0M2xBCbrAM4QJC5ny6GRy01g1ZF78LqFKo5O7TYGiZQowbQWatD2GHwWY5MfCN4oeSDEV5OG0ygPKSaZw1qWJ7wqChSVg4+peaStOlL+QwJMCl5yLv39VEAIgsmRap6thSkJ7ImQyDqfHJvCpIVnyp0cwZW8wACJ5Si0a3ZxbYZX5DM6cK7tAFpsoq2cAoARWZ/kzNl/Ud5Typaua2mq41GbixVcN0ya9i0+ZCwzSQhJtiNelTrq+zCAakb4C8yrZ2qXyKjxTuxxJ3FWTFEsYtEF2bd+RSRCPQwPGZuwII4rY7k6TjddHI56aYRnjKgkTRZvFIcSstITpTrMm1gGXTl/BD7S6+aOBCFRCCPk8S7p0OrH0HsuceGrL49nKsd6qeqJtF8zrcvEm2nY1F1m9phYb7AJEB6hCcm0Jw+V9VevCYWAyUkjGJ8PMfzoiMU8wAW0/gnTHhAi2EpBvrGjEU1a/djEVDtQqn4eOgNu65AAqsFqa9L692KkX2P2xcynyJ7/QJDa+057saIIBf75wPz1Um1apXEZ5rmOYOjGLdHZCjWveD5DRIG2xFRuMA0IbfUYM0E/DLUkOcPfd29g8Uxj+hGMjRhH1R9rcGy1r/0WYsCQ5FsNYkdNv/SJFrPRqVrlmhHEQrlb21tq4id6/egTSxc9Ce8JX1P1i9tng6iBXAhvY/o9M8XiJ6W82FXU6KRxOMvzUxp0bn3oKr9xBgG50hmsz+jRPnUvELP6PPrXeU2PWYcbcHHaSY80bce84mMiZ0w9js0EeowuCBzchL6aCRu1+3Jn4NVt2TfSAjyRBlwGTVS4jRhxhc+mbe4DWTp0qao1BIv8Dcf1it/6fE
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: sms-api-rke
    type: kubernetes.io/dockerconfigjson
