apiVersion: v1
kind: PersistentVolume
metadata:
  name: vivarium-home-dev-pv
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  nfs:
    path: /home/FCAM
    server: cfs09.cam.uchc.edu
  mountOptions:
    - nfsvers=3
