services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - smsnet

  gateway:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile.gateway
    image: ghcr.io/vivarium-collective/sms-gateway:0.0.1
    container_name: gateway
    ports:
      - "8080:8080"
    networks:
      - smsnet
    depends_on:
      - mongodb
    environment:
      - STANDALONE=False
      - MONGO_URI = "mongodb://mongodb:27017"

networks:
  smsnet:
    driver: bridge