################
# SMS API Gateway
################

FROM python:3.12.9-slim-bookworm

# configure uv
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    ca-certificates \
    make

ADD https://astral.sh/uv/install.sh /uv-installer.sh
RUN sh /uv-installer.sh && rm /uv-installer.sh
ENV PATH="/root/.local/bin/:$PATH"

# install project and deps
ADD . /app
WORKDIR /app
RUN uv venv \
    && uv sync

CMD ["make", "gateway"]
