# Use the official Python image from the Docker Hub
FROM python:3.12-slim-bookworm AS base

ARG APP_UID=17163
ARG APP_GID=10000

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    openssh-client \
    build-essential \
    gcc \
    g++ \
    python3-dev \
    postgresql-client && \
    rm -rf /var/lib/apt/lists/*

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Install uv from the GitHub Container Registry
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# create user/group
RUN groupadd -g $APP_GID appgroup && \
    useradd -m -u $APP_UID -g $APP_GID appuser

# Create psql alias script
RUN echo '#!/bin/bash\nPGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -p $POSTGRES_PORT -d $POSTGRES_DATABASE -U $POSTGRES_USER "$@"' > /usr/local/bin/dbshell && \
    chmod +x /usr/local/bin/dbshell

# Create SSH to Slurm login node alias script
RUN echo '#!/bin/bash\nssh -i $SLURM_SUBMIT_KEY_PATH -o UserKnownHostsFile=$SLURM_SUBMIT_KNOWN_HOSTS ${SLURM_SUBMIT_USER}@${SLURM_SUBMIT_HOST} "$@"' > /usr/local/bin/slurmshell && \
    chmod +x /usr/local/bin/slurmshell

USER appuser

# Set the working directory
WORKDIR /app

# Copy only the necessary files
COPY --chown=appuser:appgroup uv.lock /app/uv.lock
COPY --chown=appuser:appgroup pyproject.toml /app/pyproject.toml

# Install dependencies
RUN uv sync --frozen --no-install-project

# Copy the rest of the application code
COPY --chown=appuser:appgroup sms_api /app/sms_api
COPY --chown=appuser:appgroup tests /app/tests
COPY --chown=appuser:appgroup app /app/app
COPY --chown=appuser:appgroup alembic /app/alembic
COPY --chown=appuser:appgroup clients /app/clients
COPY --chown=appuser:appgroup pytest.ini alembic.ini README.md /app/
COPY --chown=appuser:appgroup assets/simulation /app/assets/simulation
COPY --chown=appuser:appgroup assets/*.json /app/assets/

# Sync the project
RUN uv sync --frozen

# Test the project (skip Docker-dependent tests since we're inside a container)
#RUN SKIP_DOCKER_TESTS=1 uv run python -m pytest

# Declare the volume for local cache storage
VOLUME ["/app/scratch"]

# Expose the port FastAPI will run on
EXPOSE 8000

ENV APP_DIR=/app/app
ENV ASSETS_DIR=/app/assets

# Command to run the application
CMD ["uv", "run", "uvicorn", "sms_api.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
