# Use the official Python image from the Docker Hub
FROM python:3.13.2-slim-bookworm AS base

# Set environment variables
ENV POETRY_VERSION=2.1.3 \
    POETRY_VIRTUALENVS_CREATE=false \
    PYTHONUNBUFFERED=1


# Install Poetry
RUN pip install "poetry==$POETRY_VERSION"

# Set the working directory
WORKDIR /app

# Copy only the necessary files
COPY pyproject.toml poetry.lock /app/

# Install dependencies
RUN poetry install --no-root --only main

# Copy the rest of the application code
COPY . /app

# Declare the volume for local cache storage
VOLUME ["/app/scratch"]

# Expose the port FastAPI will run on
EXPOSE 8888

# Command to run the application
CMD ["uvicorn", "sms_api.api.main:app", "--host", "0.0.0.0", "--port", "8888"]
