# Use the official Python image from the Docker Hub
FROM python:3.13.2-slim-bookworm AS base

# Set environment variables
ENV POETRY_VERSION=2.1.3 \
    POETRY_VIRTUALENVS_CREATE=false \
    PYTHONUNBUFFERED=1 \
    MAX_WORKERS=11


# Install Poetry
RUN pip install "poetry==$POETRY_VERSION"

# Set the working directory
WORKDIR /app

# Copy only the necessary files
COPY pyproject.toml poetry.lock /app/

# Install dependencies
RUN poetry install --no-root --only main

# Copy the rest of the application code
COPY . /app

# Command to run the application
CMD ["poetry", "run", "python", "sms_api/worker/main.py"]
