# Use the official Python image from the Docker Hub
FROM python:3.12-slim-bookworm AS base

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    openssh-client && \
    rm -rf /var/lib/apt/lists/*

# Set environment variables
ENV PYTHONUNBUFFERED=1

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

# Set the working directory
WORKDIR /app

# Copy only the necessary files
COPY uv.lock /app/uv.lock
COPY pyproject.toml /app/pyproject.toml

# Install dependencies
RUN uv sync --frozen --no-install-project

# Copy the rest of the application code
COPY . /app

# Sync the project
RUN uv sync --frozen

# Declare the volume for local cache storage
VOLUME ["/app/scratch"]

# Expose the port FastAPI will run on
EXPOSE 8000

ENV APP_DIR=/app/app
ENV ASSETS_DIR=/app/assets

# Command to run the application
CMD ["uv", "run", "uvicorn", "sms_api.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
