site_name: sms-api
repo_url: https://github.com/vivarium-collective/sms-api
site_url: https://vivarium-collective.github.io/sms-api
site_description: This is the api server for Vivarium simulation services.
site_author: Alex Patrie
edit_uri: edit/main/docs/
repo_name: vivarium-collective/sms-api
copyright: Maintained by <a href="https://vivarium-collective.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('.')
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vivarium-collective/sms-api
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/sms-api

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
