import asyncio
import gzip
import io
import json
import logging
import os
import random
import string
import tarfile
import uuid
from collections.abc import AsyncIterator
from pathlib import Path

from fastapi import BackgroundTasks, HTTPException
from fastapi.responses import FileResponse, Response, StreamingResponse

from sms_api.analysis.models import TsvOutputFile
from sms_api.common import StrEnumBase
from sms_api.common.handlers.simulators import upload_simulator
from sms_api.common.storage.file_paths import HPCFilePath
from sms_api.config import get_job_backend, get_settings
from sms_api.dependencies import get_database_service, get_simulation_service, get_ssh_session_service
from sms_api.simulation.database_service import DatabaseService
from sms_api.simulation.hpc_utils import get_correlation_id
from sms_api.simulation.models import (
    HpcRun,
    JobType,
    ParcaDataset,
    ParcaDatasetRequest,
    ParcaOptions,
    Simulation,
    SimulationConfig,
    SimulationRequest,
    SimulationRun,
    SimulatorVersion,
)
from sms_api.simulation.simulation_service import SimulationService

logger = logging.getLogger(__name__)


REPO_DIR = Path(__file__).parent.parent.parent.parent.absolute()
DEBUG_ARTIFACTS_DIR = REPO_DIR / "artifacts"
DEFAULT_SIMDATA_PATH = get_settings().hpc_parca_base_path / "default" / "kb" / "simData.cPickle"
# DEFAULT_SIMDATA_PATH = REPO_DIR / "assets" / "simData.cPickle"  # or, keep a remote copy (run parca along with
# repo/image build)


class SimulationAnalysisResponseType(StrEnumBase):
    FILE = "application/octet-stream"
    DATA_CONTENT = "application/octet-stream"
    STREAMING_JSON = "application/json"
    TSV = "text/tab-separated-values"
    ZIP_STREAM = "application/zip"
    GZIP_STREAM = "application/gzip"
    TAR_GZIP_STREAM = "application/gzip"


class SimulationAnalysisDataResponseType(StrEnumBase):
    """Response type for simulation data endpoint."""

    STREAMING = "streaming"
    FILE = "file"


def export_baseline_config(request: SimulationRequest) -> None:
    """Capture simulation config to disk for debugging/inspection.

    Writes the config to the artifacts/ directory at repo root.
    This directory is gitignored and used for debugging purposes only.
    """
    DEBUG_ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
    config_path = DEBUG_ARTIFACTS_DIR / f"workflow_config__{get_settings().deployment_namespace}.json"
    with open(config_path, "w") as fp:
        json.dump(request.config.model_dump(), fp, indent=3)


async def run_workflow_legacy(
    request: SimulationRequest,
    simulation_service: SimulationService,
    database_service: DatabaseService,
) -> Simulation:
    """
    Legacy workflow execution that supports uploading a new simulator.

    Parameterizes and executes a "full" e2e sms-api vEcoli workflow
    (simulator -> parca ref -> Simulation(parca -> variants -> simulation -> analyses)

    For new code, prefer run_workflow() with an existing simulator_id.
    """
    export_baseline_config(request)

    # 1. upload simulator if needed
    if request.simulator_id is not None:
        simulator = await database_service.get_simulator(request.simulator_id)
    else:
        simulator = await upload_simulator(
            commit_hash=request.simulator.git_commit_hash,  # type: ignore[union-attr]
            git_branch=request.simulator.git_branch,  # type: ignore[union-attr]
            git_repo_url=request.simulator.git_repo_url,  # type: ignore[union-attr]
            database_service=database_service,
            simulation_service_slurm=simulation_service,
        )
    # 2. create parca ds reference for the simData that will be generated by this request
    # TODO: use config hash to check if exists first
    parca_config = request.config.parca_options.model_dump()
    parca_ds = await database_service.insert_parca_dataset(
        parca_dataset_request=ParcaDatasetRequest(simulator_version=simulator, parca_config=parca_config)  # type: ignore[arg-type]
    )
    request.parca_dataset_id = parca_ds.database_id

    # 3. run simulation (save to db and insert hpc run)
    simulation = await database_service.insert_simulation(sim_request=request)
    random_string_7_hex = "".join(random.choices(string.hexdigits, k=7))
    correlation_id = get_correlation_id(
        ecoli_simulation=simulation,
        random_string=random_string_7_hex,
        simulator=simulator,  # type: ignore[arg-type]
    )
    job_id = await simulation_service.submit_ecoli_simulation_job(
        ecoli_simulation=simulation, database_service=database_service, correlation_id=correlation_id
    )
    _ = await database_service.insert_hpcrun(
        external_job_id=job_id,
        job_backend=get_job_backend(),
        job_type=JobType.SIMULATION,
        ref_id=simulation.database_id,
        correlation_id=correlation_id,
    )

    simulation.job_id = int(job_id) if job_id.isdigit() else None
    return simulation


async def run_simulation_workflow(
    database_service: DatabaseService,
    simulation_service: SimulationService,
    simulator_id: int,
    experiment_id: str,
    simulation_config_filename: str,
    num_generations: int | None = None,
    num_seeds: int | None = None,
    description: str | None = None,
    run_parca: bool | None = None,
) -> Simulation:
    """
    Simplified workflow execution with just the essential parameters.

    This assumes the simulator already exists in the database. The workflow
    configuration is read from the vEcoli repo on the HPC system, and parca
    execution is handled as part of the workflow.

    Args:
        database_service: Database service instance
        simulation_service: Simulation service instance
        simulator_id: Database ID of the simulator to use (must exist)
        experiment_id: Unique experiment identifier
        simulation_config_filename: Name of the config file in vEcoli/configs/ on HPC
        num_generations: Number of generations to simulate (optional, overrides config)
        num_seeds: Number of initial seeds/lineages (optional, overrides config)
        description: Description of the simulation (optional)
        run_parca: If `True`, the simulation parameter calculator is run prior to simulation execution, otherwise
            a cached "default" simulation parameter dataset is used.
    """
    if run_parca is None:
        run_parca = True

    settings = get_settings()

    # 1. Get the simulator (must exist)
    simulator = await database_service.get_simulator(simulator_id)
    if simulator is None:
        raise ValueError(f"Simulator with id {simulator_id} not found")

    # 2. Read the config template via the simulation service (SSH for SLURM, GitHub API for Batch)
    config_str = await simulation_service.read_config_template(
        simulator_version=simulator, config_filename=simulation_config_filename
    )

    # 3. Replace placeholders in the config template

    unique_experiment_id = f"sim{simulator.database_id}-{experiment_id}-{str(uuid.uuid4())[:4]}"
    config_str = config_str.replace("EXPERIMENT_ID_PLACEHOLDER", unique_experiment_id)
    config_str = config_str.replace("HPC_SIM_BASE_PATH_PLACEHOLDER", str(settings.hpc_sim_base_path))
    image_path = get_settings().hpc_image_base_path / f"vecoli-{simulator.git_commit_hash}.sif"
    config_str = config_str.replace("SIMULATOR_IMAGE_PATH_PLACEHOLDER", str(image_path))
    config_data = json.loads(config_str)

    # 4. Override config values if provided
    if num_generations is not None:
        config_data["generations"] = num_generations
    if num_seeds is not None:
        config_data["n_init_sims"] = num_seeds
    if description is not None:
        config_data["description"] = description
    if not run_parca:
        # expedite completion time by using cached simData
        config_data["sim_data_path"] = DEFAULT_SIMDATA_PATH.__str__()

    config = SimulationConfig(**config_data)

    # 5. Create placeholder parca dataset entry
    # Even though parca runs as part of the Nextflow workflow, we need a database entry
    # to satisfy the simulation's foreign key constraint and track the parca config.
    parca_config = config.parca_options.model_dump()
    parca_ds = await database_service.insert_parca_dataset(
        parca_dataset_request=ParcaDatasetRequest(simulator_version=simulator, parca_config=parca_config)  # type: ignore[arg-type]
    )

    # 6. Create SimulationRequest and insert simulation
    request = SimulationRequest(
        config=config,
        simulator_id=simulator_id,
        parca_dataset_id=parca_ds.database_id,
        simulation_config_filename=simulation_config_filename,
        experiment_id=unique_experiment_id,
    )
    export_baseline_config(request)
    simulation = await database_service.insert_simulation(sim_request=request)

    # 7. Generate correlation ID and submit job
    random_string_7_hex = "".join(random.choices(string.hexdigits, k=7))
    correlation_id = get_correlation_id(
        ecoli_simulation=simulation,
        random_string=random_string_7_hex,
        simulator=simulator,
    )
    job_id = await simulation_service.submit_ecoli_simulation_job(
        ecoli_simulation=simulation, database_service=database_service, correlation_id=correlation_id
    )

    # 8. Record HPC run
    _ = await database_service.insert_hpcrun(
        external_job_id=job_id,
        job_backend=get_job_backend(),
        job_type=JobType.SIMULATION,
        ref_id=simulation.database_id,
        correlation_id=correlation_id,
    )

    simulation.job_id = int(job_id) if job_id.isdigit() else None
    return simulation


async def run_parca(
    simulator: SimulatorVersion,
    simulation_service_slurm: SimulationService | None = None,
    database_service: DatabaseService | None = None,
    parca_config: ParcaOptions | None = None,
) -> ParcaDataset:
    if not simulation_service_slurm:
        simulation_service_slurm = get_simulation_service()
    if simulation_service_slurm is None:
        logger.exception("Simulation service is not initialized")
        raise HTTPException(status_code=404, detail="Simulation service is not initialized")
    if not database_service:
        database_service = get_database_service()
    if database_service is None:
        logger.exception("Simulation database service is not initialized")
        raise HTTPException(status_code=404, detail="Simulation database service is not initialized")

    parca_dataset_request = ParcaDatasetRequest(
        simulator_version=simulator, parca_config=parca_config or ParcaOptions()
    )
    parca_dataset = await database_service.insert_parca_dataset(parca_dataset_request=parca_dataset_request)

    # Submit parca job
    parca_job_id = await simulation_service_slurm.submit_parca_job(parca_dataset=parca_dataset)
    _hpc_run = await database_service.insert_hpcrun(
        external_job_id=parca_job_id,
        job_backend=get_job_backend(),
        job_type=JobType.PARCA,
        ref_id=parca_dataset.database_id,
        correlation_id="N/A",
    )

    return parca_dataset


async def get_parca_datasets(
    simulation_service_slurm: SimulationService | None = None,
    database_service: DatabaseService | None = None,
) -> list[ParcaDataset]:
    if not simulation_service_slurm:
        simulation_service_slurm = get_simulation_service()
    if simulation_service_slurm is None:
        logger.exception("Simulation service is not initialized")
        raise HTTPException(status_code=404, detail="Simulation service is not initialized")
    if not database_service:
        database_service = get_database_service()
    if database_service is None:
        logger.exception("Simulation database service is not initialized")
        raise HTTPException(status_code=404, detail="Simulation database service is not initialized")

    parca_datasets = await database_service.list_parca_datasets()
    return parca_datasets


async def get_simulation(db_service: DatabaseService, id: int) -> Simulation | None:
    return await db_service.get_simulation(simulation_id=id)


async def get_simulation_status(db_service: DatabaseService, id: int) -> SimulationRun:
    sim_record = await db_service.get_simulation(simulation_id=id)
    if sim_record is None:
        raise ValueError(f"Simulation with id {id} not found.")

    # Get the HpcRun record for this simulation to find the job ID
    hpc_run = await db_service.get_hpcrun_by_ref(ref_id=id, job_type=JobType.SIMULATION)
    if hpc_run is None:
        raise RuntimeError(f"No HPC run found for simulation {id}")

    try:
        external_job_id = hpc_run.external_job_id
    except ValueError:
        raise RuntimeError(f"Simulation {id} not yet dispatched to a job backend")

    simulation_service = get_simulation_service()
    if simulation_service is None:
        raise RuntimeError("Simulation service is not initialized")

    job_status_info = await simulation_service.get_job_status(external_job_id)
    if job_status_info is None:
        from sms_api.common.models import JobStatus

        logger.warning(f"Job {external_job_id} not yet visible in backend, returning UNKNOWN")
        return SimulationRun(id=int(id), status=JobStatus.UNKNOWN)

    return SimulationRun(id=int(id), status=job_status_info.status)


async def list_simulations(db_service: DatabaseService) -> list[Simulation]:
    return await db_service.list_simulations()


async def get_omics_outputs(
    hpc_sim_base_path: HPCFilePath, experiment_id: str, output_type: SimulationAnalysisResponseType | None = None
) -> list[TsvOutputFile] | StreamingResponse:
    exp_analysis_outdir = hpc_sim_base_path / experiment_id / "analyses"
    return await fetch_omics_outputs(exp_analysis_outdir=exp_analysis_outdir, output_type=output_type)


async def fetch_omics_outputs(
    exp_analysis_outdir: HPCFilePath, output_type: SimulationAnalysisResponseType | None = None
) -> list[TsvOutputFile] | StreamingResponse:
    if output_type is None:
        # original implementation's analysis response type, so default
        output_type = SimulationAnalysisResponseType.DATA_CONTENT

    analysis_request_cache = Path(get_settings().cache_dir)
    available_paths: list[HPCFilePath] = await get_available_omics_output_paths(
        remote_analysis_outdir=exp_analysis_outdir
    )

    # download available, preserving directory structure
    results_arr: None | list[TsvOutputFile] = None if output_type == SimulationAnalysisResponseType.GZIP_STREAM else []
    for remote_path in available_paths:
        output_i: TsvOutputFile | Path = await download_analysis_output(
            local_dir=analysis_request_cache,
            remote_path=remote_path,
            response_type=output_type,
            remote_base_dir=exp_analysis_outdir,
        )
        if isinstance(output_i, TsvOutputFile) and results_arr is not None:
            results_arr.append(output_i)
            continue
    if results_arr is None:
        # indicates streaming response desired
        return await stream_analysis_output_archive(dir_path=analysis_request_cache)
    return results_arr


async def get_available_omics_output_paths(remote_analysis_outdir: HPCFilePath) -> list[HPCFilePath]:
    cmd = f'find "{remote_analysis_outdir!s}" -type f'
    try:
        async with get_ssh_session_service().session() as ssh:
            ret, out, err = await ssh.run_command(cmd)
        paths = []
        accepted_extensions = ["tsv", "html", "csv", "txt"]
        for fp in out.splitlines():
            extension = fp.split(".")[-1]
            if extension in accepted_extensions:
                paths.append(HPCFilePath(remote_path=Path(fp)))
        return paths
    except Exception:
        logger.exception("could not get the filepaths that are available")
        return []


async def stream_tar_gz(dir_path: Path, chunk_size: int = 64 * 1024) -> AsyncIterator[bytes]:
    read_fd, write_fd = os.pipe()
    read_file = os.fdopen(read_fd, "rb")
    write_file = os.fdopen(write_fd, "wb")

    loop = asyncio.get_event_loop()

    async def create_tar() -> None:
        def _create() -> None:
            try:
                with tarfile.open(fileobj=write_file, mode="w|") as tar:
                    # Use arcname to make paths relative
                    tar.add(str(dir_path), arcname=dir_path.name)
            finally:
                write_file.close()

        await loop.run_in_executor(None, _create)

    tar_task = asyncio.create_task(create_tar())

    gzip_buffer = io.BytesIO()
    gzip_file = gzip.GzipFile(fileobj=gzip_buffer, mode="wb")

    try:
        while True:
            chunk = await loop.run_in_executor(None, read_file.read, chunk_size)

            if not chunk:
                break

            gzip_file.write(chunk)

            if gzip_buffer.tell() > 0:
                gzip_buffer.seek(0)
                compressed = gzip_buffer.read()
                gzip_buffer.seek(0)
                gzip_buffer.truncate()
                yield compressed

        gzip_file.close()
        gzip_buffer.seek(0)
        final_chunk = gzip_buffer.read()
        if final_chunk:
            yield final_chunk

    finally:
        read_file.close()
        await tar_task


def validate_path(dir_path: Path, base_allowed: Path | None = None) -> Path:
    """
    Validate and sanitize the directory path.
    Prevents path traversal attacks.
    """
    path = dir_path.resolve()

    # Optional: restrict to a base directory
    if base_allowed:
        base_allowed = base_allowed.resolve()
        if not str(path).startswith(str(base_allowed)):
            raise HTTPException(status_code=403, detail="Access denied: path outside allowed directory")

    if not path.exists():
        raise HTTPException(status_code=404, detail="Directory not found")

    if not path.is_dir():
        raise HTTPException(status_code=400, detail="Path is not a directory")

    return path


async def stream_analysis_output_archive(dir_path: Path) -> StreamingResponse:
    validated_path = validate_path(dir_path, base_allowed=None)

    # Generate a safe filename for the download
    archive_name = f"{validated_path.name}.tar.gz"

    return StreamingResponse(
        stream_tar_gz(validated_path),
        media_type="application/gzip",
        headers={
            "Content-Disposition": f'attachment; filename="{archive_name}"',
            "X-Content-Type-Options": "nosniff",
        },
    )


def create_tar_gz_archive(dir_path: Path, output_path: Path) -> Path:
    """Create a tar.gz archive of a directory and save it to disk.

    Args:
        dir_path: Directory to archive
        output_path: Path where the archive will be saved

    Returns:
        Path to the created archive
    """
    validated_path = validate_path(dir_path, base_allowed=None)

    # Create parent directories if needed
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Create the tar.gz archive
    with tarfile.open(output_path, "w:gz") as tar:
        tar.add(str(validated_path), arcname=validated_path.name)

    return output_path


def cleanup_archive_file(file_path: Path) -> None:
    """Remove the archive file after it has been sent."""
    try:
        if file_path.exists():
            file_path.unlink()
            logger.debug(f"Cleaned up temporary archive: {file_path}")
    except Exception as e:
        logger.warning(f"Failed to clean up archive file {file_path}: {e}")


async def file_analysis_output_archive(dir_path: Path, bg_tasks: BackgroundTasks, experiment_id: str) -> FileResponse:
    """Create a tar.gz archive and return it as a FileResponse for direct download.

    The archive is saved to disk temporarily and cleaned up after the response is sent.
    """
    validated_path = validate_path(dir_path, base_allowed=None)

    # Generate archive filename and path
    archive_name = f"{experiment_id}.tar.gz"
    archive_path = Path(get_settings().cache_dir) / "downloads" / archive_name

    # Create the archive
    create_tar_gz_archive(validated_path, archive_path)

    # Schedule cleanup after response is sent
    bg_tasks.add_task(cleanup_archive_file, archive_path)

    return FileResponse(
        path=archive_path,
        filename=archive_name,
        media_type="application/gzip",
        headers={
            "Content-Disposition": f'attachment; filename="{archive_name}"',
            "X-Content-Type-Options": "nosniff",
        },
    )


async def download_analysis_output(
    local_dir: Path,
    remote_path: HPCFilePath,
    response_type: SimulationAnalysisResponseType,
    remote_base_dir: HPCFilePath | None = None,
) -> TsvOutputFile | Path:
    """Download a remote analysis output file to local cache.

    Args:
        local_dir: Local directory to save files to
        remote_path: Full remote path to the file
        response_type: Type of response to return
        remote_base_dir: Base remote directory for calculating relative paths.
            If provided, the directory structure relative to this base will be
            preserved locally. If None, only the filename is used (legacy behavior).
    """
    accepted_response_types = SimulationAnalysisResponseType.values()
    if response_type not in accepted_response_types:
        raise ValueError(
            f"Unexpected response_type. Got: {response_type}; Expected one of: {accepted_response_types!s}"
        )

    # Calculate relative path to preserve directory structure
    if remote_base_dir is not None:
        relative_path = remote_path.remote_path.relative_to(remote_base_dir.remote_path)
        local = local_dir / relative_path
    else:
        # Legacy behavior: just use filename
        relative_path = Path(remote_path.remote_path.parts[-1])
        local = local_dir / relative_path

    # Create parent directories if needed
    local.parent.mkdir(parents=True, exist_ok=True)

    if not local.exists():
        async with get_ssh_session_service().session() as ssh:
            await ssh.scp_download(local_file=local, remote_path=remote_path)

    if response_type == SimulationAnalysisResponseType.DATA_CONTENT:
        return TsvOutputFile(filename=str(relative_path), content=local.read_text())
    elif response_type == SimulationAnalysisResponseType.TAR_GZIP_STREAM:
        return local
    raise RuntimeError("Not sure how you got here, but here you are. Cheers!")


async def get_simulation_outputs(
    db_service: DatabaseService,
    simulation_id: int,
    hpc_sim_base_path: HPCFilePath,
    data_response_type: SimulationAnalysisDataResponseType = SimulationAnalysisDataResponseType.STREAMING,
    bg_tasks: BackgroundTasks | None = None,
) -> StreamingResponse | FileResponse:
    """Get simulation outputs as a tar.gz archive.

    Args:
        db_service: Database service instance
        simulation_id: ID of the simulation to get outputs for
        hpc_sim_base_path: Base path for simulation outputs on HPC
        data_response_type: Type of response - STREAMING for chunked streaming,
            FILE for direct file download
        bg_tasks: Background tasks for cleanup (required for FILE response type)

    Returns:
        StreamingResponse or FileResponse containing the tar.gz archive
    """
    simulation = await db_service.get_simulation(simulation_id=simulation_id)
    if simulation is None:
        raise ValueError(f"Simulation with id {simulation_id} not found in database.")

    # Check backend — data download currently requires SSH (SLURM only)
    hpc_run = await db_service.get_hpcrun_by_ref(ref_id=simulation_id, job_type=JobType.SIMULATION)
    if hpc_run is not None and hpc_run.job_backend != "slurm":
        raise HTTPException(
            status_code=501,
            detail=f"Output download is not yet supported for the '{hpc_run.job_backend}' backend. "
            "Batch outputs should be retrieved directly from S3.",
        )

    experiment_id = simulation.config.experiment_id
    exp_analysis_outdir = hpc_sim_base_path / experiment_id / "analyses"

    # Download files to local cache, preserving directory structure
    analysis_request_cache = Path(get_settings().cache_dir) / experiment_id
    if not analysis_request_cache.exists():
        analysis_request_cache.mkdir(parents=True)
    available_paths: list[HPCFilePath] = await get_available_omics_output_paths(
        remote_analysis_outdir=exp_analysis_outdir
    )
    for remote_path in available_paths:
        await download_analysis_output(
            local_dir=analysis_request_cache,
            remote_path=remote_path,
            response_type=SimulationAnalysisResponseType.TAR_GZIP_STREAM,
            remote_base_dir=exp_analysis_outdir,
        )

    # Return appropriate response type
    if data_response_type == SimulationAnalysisDataResponseType.FILE:
        if bg_tasks is None:
            raise ValueError("BackgroundTasks required for FILE response type")
        return await file_analysis_output_archive(
            dir_path=analysis_request_cache, bg_tasks=bg_tasks, experiment_id=experiment_id
        )
    else:
        return await stream_analysis_output_archive(dir_path=analysis_request_cache)


async def get_simulation_log(db_service: DatabaseService, simulation_id: int) -> Response:
    hpc_run: HpcRun | None = await db_service.get_hpcrun_by_ref(ref_id=simulation_id, job_type=JobType.SIMULATION)
    if hpc_run is None:
        raise ValueError(f"No hpc run found for simulation with id: {simulation_id}")

    if hpc_run.job_backend != "slurm":
        raise HTTPException(
            status_code=501,
            detail=f"Log retrieval is not yet supported for the '{hpc_run.job_backend}' backend. "
            "Batch job logs are available in AWS CloudWatch.",
        )

    stdout = await _get_slurm_log(hpc_run)
    _, _, after = stdout.partition("N E X T F L O W")
    result = "N E X T F L O W" + after
    return Response(content=result, media_type="text/plain")


async def _get_slurm_log(hpc_run: HpcRun) -> str:
    job_id = hpc_run.slurmjobid
    log_stdout = None
    async with get_ssh_session_service().session() as ssh:
        returncode, stdout, stderr = await ssh.run_command(f"scontrol show job {job_id}")
        try:
            k = "JobName="
            job_name = next(filter(lambda v: k in v, stdout.replace("\n", "").split(" "))).replace(k, "")
            log_path = get_settings().slurm_log_base_path / f"{job_name}.out"
            _, log_stdout, _ = await ssh.run_command(f"cat {log_path!s}")
        except StopIteration:
            raise RuntimeError(f"No simulation job name available for HPC run {hpc_run.database_id}")
    return log_stdout
