import asyncio
import gzip
import io
import json
import logging
import os
import random
import string
import tarfile
import uuid
from collections.abc import AsyncIterator
from pathlib import Path

from fastapi import BackgroundTasks, HTTPException
from fastapi.responses import FileResponse, Response, StreamingResponse

from sms_api.analysis.models import TsvOutputFile
from sms_api.common import StrEnumBase
from sms_api.common.handlers.simulators import upload_simulator
from sms_api.common.hpc.job_service import JobStatusUpdate
from sms_api.common.models import JobBackend, JobStatus, SSHTarget
from sms_api.common.simulator_defaults import DEFAULT_OBSERVABLES
from sms_api.common.storage.file_paths import HPCFilePath, S3FilePath
from sms_api.config import get_job_backend, get_settings
from sms_api.dependencies import get_database_service, get_file_service, get_simulation_service, get_ssh_session_service
from sms_api.simulation.database_service import DatabaseService
from sms_api.simulation.hpc_utils import get_correlation_id
from sms_api.simulation.models import (
    AnalysisOptions,
    HpcRun,
    JobType,
    ParcaDataset,
    ParcaDatasetRequest,
    ParcaOptions,
    Simulation,
    SimulationConfig,
    SimulationRequest,
    SimulationRun,
    SimulatorVersion,
)
from sms_api.simulation.simulation_service import SimulationService

logger = logging.getLogger(__name__)


REPO_DIR = Path(__file__).parent.parent.parent.parent.absolute()
DEBUG_ARTIFACTS_DIR = REPO_DIR / "artifacts"
DEFAULT_SIMDATA_PATH = get_settings().hpc_parca_base_path / "default" / "kb" / "simData.cPickle"
# DEFAULT_SIMDATA_PATH = REPO_DIR / "assets" / "simData.cPickle"  # or, keep a remote copy (run parca along with
# repo/image build)


class SimulationAnalysisResponseType(StrEnumBase):
    FILE = "application/octet-stream"
    DATA_CONTENT = "application/octet-stream"
    STREAMING_JSON = "application/json"
    TSV = "text/tab-separated-values"
    ZIP_STREAM = "application/zip"
    GZIP_STREAM = "application/gzip"
    TAR_GZIP_STREAM = "application/gzip"


class SimulationAnalysisDataResponseType(StrEnumBase):
    """Response type for simulation data endpoint."""

    STREAMING = "streaming"
    FILE = "file"


def export_baseline_config(request: SimulationRequest) -> None:
    """Capture simulation config to disk for debugging/inspection.

    Writes the config to the artifacts/ directory at repo root.
    This directory is gitignored and used for debugging purposes only.
    """
    DEBUG_ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
    config_path = DEBUG_ARTIFACTS_DIR / f"workflow_config__{get_settings().deployment_namespace}.json"
    with open(config_path, "w") as fp:
        json.dump(request.config.model_dump(), fp, indent=3)


async def run_workflow_legacy(
    request: SimulationRequest,
    simulation_service: SimulationService,
    database_service: DatabaseService,
) -> Simulation:
    """
    Legacy workflow execution that supports uploading a new simulator.

    Parameterizes and executes a "full" e2e sms-api vEcoli workflow
    (simulator -> parca ref -> Simulation(parca -> variants -> simulation -> analyses)

    For new code, prefer run_workflow() with an existing simulator_id.
    """
    export_baseline_config(request)

    # 1. upload simulator if needed
    if request.simulator_id is not None:
        simulator = await database_service.get_simulator(request.simulator_id)
    else:
        simulator = await upload_simulator(
            commit_hash=request.simulator.git_commit_hash,  # type: ignore[union-attr]
            git_branch=request.simulator.git_branch,  # type: ignore[union-attr]
            git_repo_url=request.simulator.git_repo_url,  # type: ignore[union-attr]
            database_service=database_service,
            simulation_service_slurm=simulation_service,
        )
    # 2. create parca ds reference for the simData that will be generated by this request
    # TODO: use config hash to check if exists first
    parca_config = request.config.parca_options.model_dump()
    parca_ds = await database_service.insert_parca_dataset(
        parca_dataset_request=ParcaDatasetRequest(simulator_version=simulator, parca_config=parca_config)  # type: ignore[arg-type]
    )
    request.parca_dataset_id = parca_ds.database_id

    # 3. run simulation (save to db and insert hpc run)
    simulation = await database_service.insert_simulation(sim_request=request)
    random_string_7_hex = "".join(random.choices(string.hexdigits, k=7))
    correlation_id = get_correlation_id(
        ecoli_simulation=simulation,
        random_string=random_string_7_hex,
        simulator=simulator,  # type: ignore[arg-type]
    )
    job_id = await simulation_service.submit_ecoli_simulation_job(
        ecoli_simulation=simulation, database_service=database_service, correlation_id=correlation_id
    )
    _ = await database_service.insert_hpcrun(
        job_id=job_id,
        job_type=JobType.SIMULATION,
        ref_id=simulation.database_id,
        correlation_id=correlation_id,
    )

    simulation.job_id = str(job_id)
    return simulation


async def _verify_build_complete(database_service: DatabaseService, simulator_id: int) -> None:
    """Raise ValueError if the simulator build is still running or failed."""
    build_run = await database_service.get_hpcrun_by_ref(ref_id=simulator_id, job_type=JobType.BUILD_IMAGE)
    if build_run is None:
        return
    if build_run.status in (JobStatus.RUNNING, JobStatus.PENDING):
        raise ValueError(
            f"Simulator {simulator_id} build is still in progress (status: {build_run.status.value}). "
            "Wait for the build to complete before submitting a simulation."
        )
    if build_run.status == JobStatus.FAILED:
        raise ValueError(
            f"Simulator {simulator_id} build failed: {build_run.error_message or 'unknown error'}. "
            "Re-upload the simulator to retry."
        )


# TODO: formalize config template overwrite logic to favor dataclasses over dict mutation


async def run_simulation_workflow(  # noqa: C901
    database_service: DatabaseService,
    simulation_service: SimulationService,
    simulator_id: int,
    experiment_id: str,
    simulation_config_filename: str,
    num_generations: int | None = None,
    num_seeds: int | None = None,
    description: str | None = None,
    run_parca: bool | None = None,
    observables: list[str] | None = None,
    analysis_options: AnalysisOptions | None = None,
) -> Simulation:
    """
    Simplified workflow execution with just the essential parameters.

    This assumes the simulator already exists in the database. The workflow
    configuration is read from the vEcoli repo on the HPC system, and parca
    execution is handled as part of the workflow.

    Args:
        database_service: Database service instance
        simulation_service: Simulation service instance
        simulator_id: Database ID of the simulator to use (must exist)
        experiment_id: Unique experiment identifier
        simulation_config_filename: Name of the config file in vEcoli/configs/ on HPC
        num_generations: Number of generations to simulate (optional, overrides config)
        num_seeds: Number of initial seeds/lineages (optional, overrides config)
        description: Description of the simulation (optional)
        run_parca: If `True`, the simulation parameter calculator is run prior to simulation execution, otherwise
            a cached "default" simulation parameter dataset is used.
        observables: a flat, list of strings representing dot-delimited hierarchical paths within the vEcoli output, for
            otherwise comma-delimited hierarchical paths to exclusively include in the output reporting.
        analysis_options: Analysis options specific to the vecoli workflow API, corresponding to specific existing
            analysis modules in the vecoli repo.
    """
    if run_parca is None:
        run_parca = True

    settings = get_settings()

    # 1. Get the simulator (must exist)
    simulator = await database_service.get_simulator(simulator_id)
    if simulator is None:
        raise ValueError(f"Simulator with id {simulator_id} not found")

    # Verify simulator build is complete before submitting simulation
    await _verify_build_complete(database_service, simulator_id)

    # 2. Read the config template via the simulation service (SSH for SLURM, GitHub API for K8s)
    config_str = await simulation_service.read_config_template(
        simulator_version=simulator, config_filename=simulation_config_filename
    )

    # 3. Replace placeholders in the config template

    unique_experiment_id = f"sim{simulator.database_id}-{experiment_id}-{str(uuid.uuid4())[:4]}"
    config_str = config_str.replace("EXPERIMENT_ID_PLACEHOLDER", unique_experiment_id)
    config_str = config_str.replace("HPC_SIM_BASE_PATH_PLACEHOLDER", str(settings.hpc_sim_base_path))
    image_path = get_settings().hpc_image_base_path / f"vecoli-{simulator.git_commit_hash}.sif"
    config_str = config_str.replace("SIMULATOR_IMAGE_PATH_PLACEHOLDER", str(image_path))
    config_data = json.loads(config_str)

    # 4. Override config values if provided
    if num_generations is not None:
        config_data["generations"] = num_generations
    if num_seeds is not None:
        config_data["n_init_sims"] = num_seeds
    if description is not None:
        config_data["description"] = description
    effective_observables = observables if observables else DEFAULT_OBSERVABLES
    config_data["engine_process_reports"] = [obs.split(".") for obs in effective_observables]
    # For K8s/Batch backend, override HPC paths with AWS equivalents
    if get_job_backend() == "k8s":
        s3_output = f"s3://{settings.s3_work_bucket}/{settings.s3_output_prefix}/{unique_experiment_id}"
        config_data["emitter_arg"] = {"out_uri": s3_output}
        config_data.pop("aws_cdk", None)
        config_data.pop("ccam", None)
        config_data["progress_bar"] = False
        if "parca_options" in config_data:
            config_data["parca_options"]["outdir"] = s3_output
        # Use short image name (repo:tag) — workflow.py resolves the full ECR URI
        # via build-and-push-ecr.sh -u at runtime
        config_data["aws"] = {
            "build_image": False,
            "container_image": f"{settings.ecr_repository}:{simulator.git_commit_hash}-{settings.batch_task_arch}",
            "region": settings.batch_region,
            "batch_queue": settings.batch_arm64_queue
            if settings.batch_task_arch == "arm64"
            else settings.batch_amd64_queue,
        }
        if not run_parca:
            # Set local path for cached simData — the K8s job command will download
            # from S3 to this path before workflow.py runs (vEcoli only accepts local paths)
            config_data["sim_data_path"] = "/tmp/simData.cPickle"  # noqa: S108
    elif not run_parca:
        # SLURM: use cached simData from HPC filesystem
        config_data["sim_data_path"] = DEFAULT_SIMDATA_PATH.__str__()

    specified_analyses = {
        "multiseed": {
            "cd1_metabolomics": {"generation_lower_bound": 5},
            "cd1_transcriptomics": {"generation_lower_bound": 5},
            "cd1_higher_order_properties": {"generation_lower_bound": 5},
            "cd1_fluxomics": {"generation_lower_bound": 5},
            "cd1_proteomics": {"generation_lower_bound": 5},
        }
    }
    if analysis_options is not None:
        specified_analyses = analysis_options.model_dump()

    config_data["analysis_options"] = specified_analyses
    config = SimulationConfig(**config_data)

    # 5. Create placeholder parca dataset entry
    # Even though parca runs as part of the Nextflow workflow, we need a database entry
    # to satisfy the simulation's foreign key constraint and track the parca config.
    parca_config = config.parca_options.model_dump()
    parca_ds = await database_service.insert_parca_dataset(
        parca_dataset_request=ParcaDatasetRequest(simulator_version=simulator, parca_config=parca_config)  # type: ignore[arg-type]
    )

    # 6. Create SimulationRequest and insert simulation
    request = SimulationRequest(
        config=config,
        simulator_id=simulator_id,
        parca_dataset_id=parca_ds.database_id,
        simulation_config_filename=simulation_config_filename,
        experiment_id=unique_experiment_id,
    )
    export_baseline_config(request)
    simulation = await database_service.insert_simulation(sim_request=request)

    # 7. Generate correlation ID and submit job
    random_string_7_hex = "".join(random.choices(string.hexdigits, k=7))
    correlation_id = get_correlation_id(
        ecoli_simulation=simulation,
        random_string=random_string_7_hex,
        simulator=simulator,
    )
    job_id = await simulation_service.submit_ecoli_simulation_job(
        ecoli_simulation=simulation, database_service=database_service, correlation_id=correlation_id
    )

    # 8. Record HPC run
    _ = await database_service.insert_hpcrun(
        job_id=job_id,
        job_type=JobType.SIMULATION,
        ref_id=simulation.database_id,
        correlation_id=correlation_id,
    )

    simulation.job_id = str(job_id)
    return simulation


async def run_parca(
    simulator: SimulatorVersion,
    simulation_service_slurm: SimulationService | None = None,
    database_service: DatabaseService | None = None,
    parca_config: ParcaOptions | None = None,
) -> ParcaDataset:
    if not simulation_service_slurm:
        simulation_service_slurm = get_simulation_service()
    if simulation_service_slurm is None:
        logger.exception("Simulation service is not initialized")
        raise HTTPException(status_code=404, detail="Simulation service is not initialized")
    if not database_service:
        database_service = get_database_service()
    if database_service is None:
        logger.exception("Simulation database service is not initialized")
        raise HTTPException(status_code=404, detail="Simulation database service is not initialized")

    parca_dataset_request = ParcaDatasetRequest(
        simulator_version=simulator, parca_config=parca_config or ParcaOptions()
    )
    parca_dataset = await database_service.insert_parca_dataset(parca_dataset_request=parca_dataset_request)

    # Submit parca job
    parca_job_id = await simulation_service_slurm.submit_parca_job(parca_dataset=parca_dataset)
    _hpc_run = await database_service.insert_hpcrun(
        job_id=parca_job_id,
        job_type=JobType.PARCA,
        ref_id=parca_dataset.database_id,
        correlation_id="N/A",
    )

    return parca_dataset


async def get_parca_datasets(
    simulation_service_slurm: SimulationService | None = None,
    database_service: DatabaseService | None = None,
) -> list[ParcaDataset]:
    if not simulation_service_slurm:
        simulation_service_slurm = get_simulation_service()
    if simulation_service_slurm is None:
        logger.exception("Simulation service is not initialized")
        raise HTTPException(status_code=404, detail="Simulation service is not initialized")
    if not database_service:
        database_service = get_database_service()
    if database_service is None:
        logger.exception("Simulation database service is not initialized")
        raise HTTPException(status_code=404, detail="Simulation database service is not initialized")

    parca_datasets = await database_service.list_parca_datasets()
    return parca_datasets


async def get_simulation(db_service: DatabaseService, id: int) -> Simulation | None:
    return await db_service.get_simulation(simulation_id=id)


async def get_simulation_status(db_service: DatabaseService, id: int) -> SimulationRun:
    sim_record = await db_service.get_simulation(simulation_id=id)
    if sim_record is None:
        raise ValueError(f"Simulation with id {id} not found.")

    # Get the HpcRun record for this simulation to find the job ID
    hpc_run = await db_service.get_hpcrun_by_ref(ref_id=id, job_type=JobType.SIMULATION)
    if hpc_run is None:
        raise RuntimeError(f"No HPC run found for simulation {id}")

    simulation_service = get_simulation_service()
    if simulation_service is None:
        raise RuntimeError("Simulation service is not initialized")

    job_status_info = await simulation_service.get_job_status(hpc_run.job_id)
    if job_status_info is None:
        logger.warning(f"Job {hpc_run.job_id} not yet visible in backend, returning UNKNOWN")
        return SimulationRun(id=int(id), status=JobStatus.UNKNOWN)

    # Persist terminal status to DB so future calls don't need to hit the backend
    if job_status_info.status in (JobStatus.COMPLETED, JobStatus.FAILED, JobStatus.CANCELLED):
        update = JobStatusUpdate(
            job_id=hpc_run.job_id,
            status=job_status_info.status,
            start_time=job_status_info.start_time,
            end_time=job_status_info.end_time,
            error_message=job_status_info.error_message,
        )
        await db_service.update_hpcrun_status(hpcrun_id=hpc_run.database_id, update=update)

    return SimulationRun(id=int(id), status=job_status_info.status, error_message=job_status_info.error_message)


async def cancel_simulation(
    db_service: DatabaseService,
    simulation_service: SimulationService,
    simulation_id: int,
) -> SimulationRun:
    """Cancel a running simulation by killing its backend job."""
    hpc_run = await db_service.get_hpcrun_by_ref(ref_id=simulation_id, job_type=JobType.SIMULATION)
    if hpc_run is None:
        raise ValueError(f"No HPC run found for simulation {simulation_id}")

    # Only cancel jobs that are still active
    if hpc_run.status in (JobStatus.COMPLETED, JobStatus.FAILED, JobStatus.CANCELLED):
        return SimulationRun(id=simulation_id, status=hpc_run.status)

    # Cancel the backend job
    await simulation_service.cancel_job(hpc_run.job_id)

    # Update the database record
    update = JobStatusUpdate(
        job_id=hpc_run.job_id,
        status=JobStatus.CANCELLED,
    )
    await db_service.update_hpcrun_status(hpcrun_id=hpc_run.database_id, update=update)

    return SimulationRun(id=simulation_id, status=JobStatus.CANCELLED)


async def list_simulations(db_service: DatabaseService) -> list[Simulation]:
    return await db_service.list_simulations()


async def get_omics_outputs(
    hpc_sim_base_path: HPCFilePath, experiment_id: str, output_type: SimulationAnalysisResponseType | None = None
) -> list[TsvOutputFile] | StreamingResponse:
    exp_analysis_outdir = hpc_sim_base_path / experiment_id / "analyses"
    return await fetch_omics_outputs(exp_analysis_outdir=exp_analysis_outdir, output_type=output_type)


async def fetch_omics_outputs(
    exp_analysis_outdir: HPCFilePath, output_type: SimulationAnalysisResponseType | None = None
) -> list[TsvOutputFile] | StreamingResponse:
    if output_type is None:
        # original implementation's analysis response type, so default
        output_type = SimulationAnalysisResponseType.DATA_CONTENT

    analysis_request_cache = Path(get_settings().cache_dir)
    available_paths: list[HPCFilePath] = await get_available_omics_output_paths(
        remote_analysis_outdir=exp_analysis_outdir
    )

    # download available, preserving directory structure
    results_arr: None | list[TsvOutputFile] = None if output_type == SimulationAnalysisResponseType.GZIP_STREAM else []
    for remote_path in available_paths:
        output_i: TsvOutputFile | Path = await download_analysis_output(
            local_dir=analysis_request_cache,
            remote_path=remote_path,
            response_type=output_type,
            remote_base_dir=exp_analysis_outdir,
        )
        if isinstance(output_i, TsvOutputFile) and results_arr is not None:
            results_arr.append(output_i)
            continue
    if results_arr is None:
        # indicates streaming response desired
        return await stream_analysis_output_archive(dir_path=analysis_request_cache)
    return results_arr


async def get_available_omics_output_paths(remote_analysis_outdir: HPCFilePath) -> list[HPCFilePath]:
    cmd = f'find "{remote_analysis_outdir!s}" -type f'
    try:
        async with get_ssh_session_service(SSHTarget.SLURM).session() as ssh:
            ret, out, err = await ssh.run_command(cmd)
        paths = []
        accepted_extensions = ["tsv", "html", "csv", "txt"]
        for fp in out.splitlines():
            extension = fp.split(".")[-1]
            if extension in accepted_extensions:
                paths.append(HPCFilePath(remote_path=Path(fp)))
        return paths
    except Exception:
        logger.exception("could not get the filepaths that are available")
        return []


async def stream_tar_gz(dir_path: Path, chunk_size: int = 64 * 1024) -> AsyncIterator[bytes]:
    read_fd, write_fd = os.pipe()
    read_file = os.fdopen(read_fd, "rb")
    write_file = os.fdopen(write_fd, "wb")

    loop = asyncio.get_event_loop()

    async def create_tar() -> None:
        def _create() -> None:
            try:
                with tarfile.open(fileobj=write_file, mode="w|") as tar:
                    # Use arcname to make paths relative
                    tar.add(str(dir_path), arcname=dir_path.name)
            finally:
                write_file.close()

        await loop.run_in_executor(None, _create)

    tar_task = asyncio.create_task(create_tar())

    gzip_buffer = io.BytesIO()
    gzip_file = gzip.GzipFile(fileobj=gzip_buffer, mode="wb")

    try:
        while True:
            chunk = await loop.run_in_executor(None, read_file.read, chunk_size)

            if not chunk:
                break

            gzip_file.write(chunk)

            if gzip_buffer.tell() > 0:
                gzip_buffer.seek(0)
                compressed = gzip_buffer.read()
                gzip_buffer.seek(0)
                gzip_buffer.truncate()
                yield compressed

        gzip_file.close()
        gzip_buffer.seek(0)
        final_chunk = gzip_buffer.read()
        if final_chunk:
            yield final_chunk

    finally:
        read_file.close()
        await tar_task


def validate_path(dir_path: Path, base_allowed: Path | None = None) -> Path:
    """
    Validate and sanitize the directory path.
    Prevents path traversal attacks.
    """
    path = dir_path.resolve()

    # Optional: restrict to a base directory
    if base_allowed:
        base_allowed = base_allowed.resolve()
        if not str(path).startswith(str(base_allowed)):
            raise HTTPException(status_code=403, detail="Access denied: path outside allowed directory")

    if not path.exists():
        raise HTTPException(status_code=404, detail="Directory not found")

    if not path.is_dir():
        raise HTTPException(status_code=400, detail="Path is not a directory")

    return path


async def stream_analysis_output_archive(dir_path: Path) -> StreamingResponse:
    validated_path = validate_path(dir_path, base_allowed=None)

    # Generate a safe filename for the download
    archive_name = f"{validated_path.name}.tar.gz"

    return StreamingResponse(
        stream_tar_gz(validated_path),
        media_type="application/gzip",
        headers={
            "Content-Disposition": f'attachment; filename="{archive_name}"',
            "X-Content-Type-Options": "nosniff",
        },
    )


def create_tar_gz_archive(dir_path: Path, output_path: Path) -> Path:
    """Create a tar.gz archive of a directory and save it to disk.

    Args:
        dir_path: Directory to archive
        output_path: Path where the archive will be saved

    Returns:
        Path to the created archive
    """
    validated_path = validate_path(dir_path, base_allowed=None)

    # Create parent directories if needed
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Create the tar.gz archive
    with tarfile.open(output_path, "w:gz") as tar:
        tar.add(str(validated_path), arcname=validated_path.name)

    return output_path


def cleanup_archive_file(file_path: Path) -> None:
    """Remove the archive file after it has been sent."""
    try:
        if file_path.exists():
            file_path.unlink()
            logger.debug(f"Cleaned up temporary archive: {file_path}")
    except Exception as e:
        logger.warning(f"Failed to clean up archive file {file_path}: {e}")


async def file_analysis_output_archive(dir_path: Path, bg_tasks: BackgroundTasks, experiment_id: str) -> FileResponse:
    """Create a tar.gz archive and return it as a FileResponse for direct download.

    The archive is saved to disk temporarily and cleaned up after the response is sent.
    """
    validated_path = validate_path(dir_path, base_allowed=None)

    # Generate archive filename and path
    archive_name = f"{experiment_id}.tar.gz"
    archive_path = Path(get_settings().cache_dir) / "downloads" / archive_name

    # Create the archive
    create_tar_gz_archive(validated_path, archive_path)

    # Schedule cleanup after response is sent
    bg_tasks.add_task(cleanup_archive_file, archive_path)

    return FileResponse(
        path=archive_path,
        filename=archive_name,
        media_type="application/gzip",
        headers={
            "Content-Disposition": f'attachment; filename="{archive_name}"',
            "X-Content-Type-Options": "nosniff",
        },
    )


async def download_analysis_output(
    local_dir: Path,
    remote_path: HPCFilePath,
    response_type: SimulationAnalysisResponseType,
    remote_base_dir: HPCFilePath | None = None,
) -> TsvOutputFile | Path:
    """Download a remote analysis output file to local cache.

    Args:
        local_dir: Local directory to save files to
        remote_path: Full remote path to the file
        response_type: Type of response to return
        remote_base_dir: Base remote directory for calculating relative paths.
            If provided, the directory structure relative to this base will be
            preserved locally. If None, only the filename is used (legacy behavior).
    """
    accepted_response_types = SimulationAnalysisResponseType.values()
    if response_type not in accepted_response_types:
        raise ValueError(
            f"Unexpected response_type. Got: {response_type}; Expected one of: {accepted_response_types!s}"
        )

    # Calculate relative path to preserve directory structure
    if remote_base_dir is not None:
        relative_path = remote_path.remote_path.relative_to(remote_base_dir.remote_path)
        local = local_dir / relative_path
    else:
        # Legacy behavior: just use filename
        relative_path = Path(remote_path.remote_path.parts[-1])
        local = local_dir / relative_path

    # Create parent directories if needed
    local.parent.mkdir(parents=True, exist_ok=True)

    if not local.exists():
        async with get_ssh_session_service(SSHTarget.SLURM).session() as ssh:
            await ssh.scp_download(local_file=local, remote_path=remote_path)

    if response_type == SimulationAnalysisResponseType.DATA_CONTENT:
        return TsvOutputFile(filename=str(relative_path), content=local.read_text())
    elif response_type == SimulationAnalysisResponseType.TAR_GZIP_STREAM:
        return local
    raise RuntimeError("Not sure how you got here, but here you are. Cheers!")


async def get_simulation_outputs(
    db_service: DatabaseService,
    simulation_id: int,
    hpc_sim_base_path: HPCFilePath,
    data_response_type: SimulationAnalysisDataResponseType = SimulationAnalysisDataResponseType.STREAMING,
    bg_tasks: BackgroundTasks | None = None,
) -> StreamingResponse | FileResponse:
    """Get simulation outputs as a tar.gz archive.

    Dispatches to SSH/SCP (SLURM backend) or S3 (K8s/LOCAL backend) based on the HpcRun record.
    """
    simulation = await db_service.get_simulation(simulation_id=simulation_id)
    if simulation is None:
        raise ValueError(f"Simulation with id {simulation_id} not found in database.")

    experiment_id = simulation.config.experiment_id

    # Download files to local cache, preserving directory structure
    analysis_request_cache = Path(get_settings().cache_dir) / experiment_id
    analysis_request_cache.mkdir(parents=True, exist_ok=True)

    # Dispatch based on backend
    hpc_run = await db_service.get_hpcrun_by_ref(ref_id=simulation_id, job_type=JobType.SIMULATION)
    if hpc_run and hpc_run.job_id.backend in (JobBackend.K8S, JobBackend.LOCAL):
        await _download_outputs_from_s3(experiment_id, analysis_request_cache)
    else:
        # SLURM path: download via SSH/SCP
        exp_analysis_outdir = hpc_sim_base_path / experiment_id / "analyses"
        available_paths: list[HPCFilePath] = await get_available_omics_output_paths(
            remote_analysis_outdir=exp_analysis_outdir
        )
        for remote_path in available_paths:
            await download_analysis_output(
                local_dir=analysis_request_cache,
                remote_path=remote_path,
                response_type=SimulationAnalysisResponseType.TAR_GZIP_STREAM,
                remote_base_dir=exp_analysis_outdir,
            )

    # Return appropriate response type (same for both backends)
    if data_response_type == SimulationAnalysisDataResponseType.FILE:
        if bg_tasks is None:
            raise ValueError("BackgroundTasks required for FILE response type")
        return await file_analysis_output_archive(
            dir_path=analysis_request_cache, bg_tasks=bg_tasks, experiment_id=experiment_id
        )
    else:
        return await stream_analysis_output_archive(dir_path=analysis_request_cache)


_ACCEPTED_ANALYSES_EXTENSIONS = (".tsv", ".json")
_WORKFLOW_CONFIG_KEY = "nextflow/workflow_config.json"


async def _download_outputs_from_s3(experiment_id: str, local_cache: Path) -> None:
    """Download simulation outputs from S3 to local cache.

    Downloads only:
    - All files under ``analyses/`` matching accepted extensions (.tsv, .json)
    - ``nextflow/workflow_config.json``
    """
    settings = get_settings()
    file_service = get_file_service()
    if file_service is None:
        raise RuntimeError("File service is not initialized")

    experiment_prefix = f"{settings.s3_output_prefix}/{experiment_id}/{experiment_id}"

    # 1. Download analyses/ contents
    analyses_prefix = S3FilePath(s3_path=Path(f"{experiment_prefix}/analyses"))
    analyses_listing = await file_service.get_listing(analyses_prefix)
    for item in analyses_listing:
        if not item.Key.endswith(_ACCEPTED_ANALYSES_EXTENSIONS):
            continue
        relative = Path(item.Key).relative_to(experiment_prefix)
        local_file = local_cache / relative
        if local_file.exists():
            continue
        local_file.parent.mkdir(parents=True, exist_ok=True)
        await file_service.download_file(S3FilePath(s3_path=Path(item.Key)), local_file)

    # 2. Download nextflow/workflow_config.json
    workflow_config_key = f"{experiment_prefix}/{_WORKFLOW_CONFIG_KEY}"
    workflow_config_s3 = S3FilePath(s3_path=Path(workflow_config_key))
    local_workflow_config = local_cache / _WORKFLOW_CONFIG_KEY
    if not local_workflow_config.exists():
        local_workflow_config.parent.mkdir(parents=True, exist_ok=True)
        try:
            await file_service.download_file(workflow_config_s3, local_workflow_config)
        except Exception:
            logger.warning(f"workflow_config.json not found at {workflow_config_key}, skipping")


async def get_simulation_log(db_service: DatabaseService, simulation_id: int, truncate: bool = True) -> Response:
    """Get simulation workflow log. Dispatches to SLURM or K8s based on backend."""
    hpc_run = await db_service.get_hpcrun_by_ref(ref_id=simulation_id, job_type=JobType.SIMULATION)
    if hpc_run is None:
        raise ValueError(f"No HPC run found for simulation {simulation_id}")

    if hpc_run.job_id.backend == JobBackend.K8S:
        log_content = await _get_k8s_log(hpc_run, db_service, simulation_id)
    elif hpc_run.job_id.backend == JobBackend.LOCAL:
        log_content = f"Logs not available for local tasks (job {hpc_run.job_id})"
    else:
        log_content = await _get_slurm_log(hpc_run)
        # Extract Nextflow section from SLURM log
        _, _, after = log_content.partition("N E X T F L O W")
        if after:
            log_content = "N E X T F L O W" + after

    if truncate:
        log_content = _truncate_log(log_content)

    return Response(content=log_content, media_type="text/plain")


_LOG_HEAD_LINES = 20
_TRUNCATION_MARKER = "\n... truncated ...\n\n"


def _truncate_log(log: str) -> str:
    """Return the head (Nextflow header) + tail (final executor block) of a log.

    The tail starts from the last line containing ``executor`` (the Nextflow
    summary block) and continues to EOF.  If no executor line is found, the
    last 15 lines are returned as the tail.
    """
    lines = log.splitlines(keepends=True)
    if len(lines) <= _LOG_HEAD_LINES + 15:
        return log  # already small enough

    head = "".join(lines[:_LOG_HEAD_LINES])

    # Find the last line containing "executor" — marks the final summary block
    tail_start = None
    for i in range(len(lines) - 1, -1, -1):
        if "executor" in lines[i].lower():
            tail_start = i
            break

    if tail_start is not None and tail_start > _LOG_HEAD_LINES:
        tail = "".join(lines[tail_start:])
    else:
        # Fallback: last 15 lines
        tail = "".join(lines[-15:])

    return head + _TRUNCATION_MARKER + tail


def workflow_log(simulation_id: int, base_url: str = "http://localhost:8080", timeout: int = 300) -> None:
    """Fetch the workflow log tail for a simulation and print it to the console.

    This is a convenience function for quick interactive debugging — it fetches
    the full log client-side, extracts the executor summary block, and prints
    it with Rich formatting.  No deploy required.

    Usage::

        from sms_api.common.handlers.simulations import workflow_log
        workflow_log(44)
    """
    from app.app_data_service import E2EDataService
    from app.cli_theme import get_console

    console = get_console()
    svc = E2EDataService(base_url=base_url, timeout=timeout)  # type: ignore[arg-type]

    with console.status("[memphis.spinner]Fetching status..."):
        run = svc.get_workflow_status(simulation_id=simulation_id)
    status = run.status.value.upper()

    with console.status("[memphis.spinner]Fetching log..."):
        log = svc.get_workflow_log(simulation_id=simulation_id, truncate=False)

    # Extract tail starting from last "executor" line
    lines = log.splitlines()
    tail_start = None
    for i in range(len(lines) - 1, -1, -1):
        if "executor" in lines[i].lower():
            tail_start = i
            break
    tail = "\n".join(lines[tail_start:]) if tail_start is not None else "\n".join(lines[-15:])

    from rich.panel import Panel

    console.print(Panel(tail, title=f"Workflow Log — sim {simulation_id}", border_style="memphis.border.info"))
    from app.cli_theme import status_border, status_style

    error_detail = f"\n{run.error_message}" if run.error_message else ""
    console.print(
        Panel(
            f"[{status_style(status.lower())}]{status}[/]{error_detail}",
            title="Simulation Status",
            border_style=status_border(status.lower()),
        )
    )


async def _get_slurm_log(hpc_run: HpcRun) -> str:
    """Read SLURM job log via SSH."""
    job_id = str(hpc_run.job_id)
    async with get_ssh_session_service(SSHTarget.SLURM).session() as ssh:
        returncode, stdout, stderr = await ssh.run_command(f"scontrol show job {job_id}")
        try:
            k = "JobName="
            job_name = next(filter(lambda v: k in v, stdout.replace("\n", "").split(" "))).replace(k, "")
            log_path = get_settings().slurm_log_base_path / f"{job_name}.out"
            _, log_stdout, _ = await ssh.run_command(f"cat {log_path!s}")
        except StopIteration:
            raise RuntimeError(f"No simulation job name available for HPC run {hpc_run.database_id}")
    return log_stdout


async def _get_k8s_log(hpc_run: HpcRun, db_service: DatabaseService, simulation_id: int) -> str:
    """Read K8s Job pod logs via the K8s API, falling back to S3 .nextflow.log."""
    from sms_api.simulation.simulation_service_k8s import SimulationServiceK8s

    simulation_service = get_simulation_service()
    if not isinstance(simulation_service, SimulationServiceK8s):
        raise TypeError("K8s logs requested but simulation service is not SimulationServiceK8s")

    # Try K8s pod logs first
    log_content = simulation_service._k8s.get_job_logs(hpc_run.job_id.value)
    if log_content is not None:
        return log_content

    # Fallback: download .nextflow.log from S3
    log_content = await _get_s3_nextflow_log(db_service, simulation_id)
    if log_content is not None:
        return log_content

    return f"No logs available for K8s Job {hpc_run.job_id.value} (pod cleaned up, S3 log not found)"


async def _get_s3_nextflow_log(db_service: DatabaseService, simulation_id: int) -> str | None:
    """Try to fetch .nextflow.log from S3 for a K8s simulation."""
    settings = get_settings()
    file_service = get_file_service()
    if file_service is None:
        return None

    simulation = await db_service.get_simulation(simulation_id=simulation_id)
    if simulation is None:
        return None

    experiment_id = simulation.config.experiment_id
    log_key = f"{settings.s3_work_prefix}/{experiment_id}/logs/.nextflow.log"
    log_s3 = S3FilePath(s3_path=Path(log_key))

    try:
        content = await file_service.get_file_contents(log_s3)
        if content:
            return content.decode("utf-8", errors="replace")
    except Exception:
        logger.debug(f"S3 .nextflow.log not found at {log_key}")

    return None
