---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: sms-api-rke
spec:
  encryptedData:
    .dockerconfigjson: AgDFxhE/phpPNp8AWj8Nh+09m/USJDzVHNWb+WYBGm3MbfJNZNNO8haumkU6ghTwmvLYJZwI6YClvlQGMh1SJud51v+wrGUG6ayTqKGDvfmKdF3vFtlZ7ZM7ud0StIozoWDesxefrXxwf+op/esIlfj7awji9sxPLUEYLvMok0yEExhAsSMEDp/vuiD34Tz4bYORZKHFb4mvBT8+KFRX4VSP16goIU+0xWSKq14CqU+P9vQ+u0JkiKRvpFzdQ4Ru83uBjjpHr2V3IpAqwSsoVMhVtB2DXmawI0MV6bRVnwa9B1ytzanbwcJvcq2P4aWRcIv/2uIFlvtsAZ/wfjcdeQ4AoEVdbxRlKoES76zLi+FUCRgLPL+DAwcmyajBM67hdwvJ8R0F4T7QAehGhajfNJHHZM0ABnQkNt4hARj36OFjHX/WdISvE2cQsAXDeJp5sjtpQpQGCvjljz1V/zJTvcsViiGBnpcjlW6K2hp679T4Kh7tu4HDrCFVthqJz5zv5HcWlDyjCqAc7jwqdg2vJDqe9i0t+s7zjt5RhbyEB/9B30DUVSUCuxB7A6bAmLYtVZT+gBous6/pPClhhPXSpdK3W8eDXW5Ey+PKviMCzK6stxPGjqt6H7qZ1PzgYQx9KFmYSHvT22cjaR2VNuglo4NjHOs75TsaXhuqmAruBQwlA9bjXybU8EwuriWfBG5sUF1Pe4ZaJ15HmgqFr4OHE7HPuhro3KyU+PWQxIGw0JT2FOQlDa0sWBlmJ6MbFMgnhbDm6d7zCSuqPazRMpvczdrxQklyBgxjF7+NeZr0LCRN9JLIG2R4W/B+Tu4u/kuco434ogl3hccqRugStKgHRT8+2HJfJZ9G+MusE3lyORO+SMSO72ZCoysh/WkC+Y09JaIei5iQ+8cB6tLJs3HFTfN/EPMuruyNmsY2uRkRm+HLX/OjpuKxzxscD8PSVg/S7437C+Fg4FNldxMzmefAVegB
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: sms-api-rke
    type: kubernetes.io/dockerconfigjson
