apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sms-api-local

replicas:
  - count: 1
    name: api
  - count: 0
    name: mongodb

components:
  - images.yaml

resources:
  - ingress.yaml
  - api-pvc.yaml
  - nats-svc.yaml
  - mongodb-pvc.yaml
  - ../secret-ghcr.yaml
  - ../secret-shared.yaml
  - ../secret-ssh.yaml
  - ../../../config/sms-api-local
  - ../../../base
