openapi: 3.1.0
info:
  title: sms-api
  version: 0.2.2
paths:
  /:
    get:
      summary: Root
      operationId: root__get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
                title: Response Root  Get
  /version:
    get:
      summary: Get Version
      operationId: get_version_version_get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: string
                title: Response Get Version Version Get
  /simulator_version:
    get:
      tags:
        - Simulations
      summary: get the list of available simulator versions
      operationId: get-simulator-version
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SimulatorVersion"
                title: Response Get-Simulator-Version
    post:
      tags:
        - Simulations
      summary: Upload a new simulator (vEcoli) version.
      operationId: insert-simulator-version
      parameters:
        - name: git_commit_hash
          in: query
          required: false
          schema:
            type: string
            description: First 7 characters of git commit hash
            title: Git Commit Hash
          description: First 7 characters of git commit hash
        - name: git_repo_url
          in: query
          required: false
          schema:
            type: string
            default: https://github.com/CovertLab/vEcoli
            title: Git Repo Url
        - name: git_branch
          in: query
          required: false
          schema:
            type: string
            default: master
            title: Git Branch
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimulatorVersion"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
  /vecoli_parca:
    post:
      tags:
        - Simulations
      summary: Run a parameter calculation
      operationId: calculate_parameters
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ParcaDatasetRequest"
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ParcaDataset"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
  /vecoli_simulation:
    post:
      tags:
        - Simulations
      summary: Submit to the db a single vEcoli simulation with given parameter overrides.
      operationId: submit-simulation
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EcoliSimulationRequest"
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EcoliSimulation"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
  /run-simulation:
    post:
      tags:
        - Simulations
      summary: Run a single vEcoli simulation with given parameter overrides
      operationId: run-simulation
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EcoliSimulationRequest"
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EcoliSimulationRun"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
  /get-results:
    get:
      tags:
        - Simulations
      summary: Get Results
      operationId: get-results
      parameters:
        - name: database_id
          in: query
          required: true
          schema:
            type: integer
            description: Database Id returned from /submit-simulation
            title: Database Id
          description: Database Id returned from /submit-simulation
        - name: git_commit_hash
          in: query
          required: false
          schema:
            type: string
            default: d24e988
            title: Git Commit Hash
      requestBody:
        content:
          application/json:
            schema:
              anyOf:
                - $ref: "#/components/schemas/Settings"
                - type: "null"
              title: Settings
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema: {}
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
components:
  schemas:
    EcoliSimulation:
      properties:
        database_id:
          type: integer
          title: Database Id
        sim_request:
          $ref: "#/components/schemas/EcoliSimulationRequest"
        hpc_run:
          anyOf:
            - $ref: "#/components/schemas/HpcRun"
            - type: "null"
      type: object
      required:
        - database_id
        - sim_request
      title: EcoliSimulation
    EcoliSimulationRequest:
      properties:
        simulator:
          $ref: "#/components/schemas/SimulatorVersion"
        parca_dataset_id:
          type: integer
          title: Parca Dataset Id
        variant_config:
          additionalProperties:
            additionalProperties:
              anyOf:
                - type: integer
                - type: number
                - type: string
            type: object
          type: object
          title: Variant Config
        total_time:
          type: number
          title: Total Time
          default: 11
      type: object
      required:
        - simulator
        - parca_dataset_id
        - variant_config
      title: EcoliSimulationRequest
    EcoliSimulationRun:
      properties:
        job_id:
          type: integer
          title: Job Id
        simulation:
          $ref: "#/components/schemas/EcoliSimulation"
        last_update:
          type: string
          title: Last Update
      type: object
      required:
        - job_id
        - simulation
      title: EcoliSimulationRun
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: "#/components/schemas/ValidationError"
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    HpcRun:
      properties:
        database_id:
          type: integer
          title: Database Id
        slurmjobid:
          anyOf:
            - type: integer
            - type: "null"
          title: Slurmjobid
        status:
          anyOf:
            - $ref: "#/components/schemas/JobStatus"
            - type: "null"
        start_time:
          anyOf:
            - type: string
            - type: "null"
          title: Start Time
        end_time:
          anyOf:
            - type: string
            - type: "null"
          title: End Time
        error_message:
          anyOf:
            - type: string
            - type: "null"
          title: Error Message
      type: object
      required:
        - database_id
      title: HpcRun
    JobStatus:
      type: string
      enum:
        - waiting
        - queued
        - running
        - completed
        - failed
      title: JobStatus
    ParcaDataset:
      properties:
        database_id:
          type: integer
          title: Database Id
        parca_dataset_request:
          $ref: "#/components/schemas/ParcaDatasetRequest"
        remote_archive_path:
          anyOf:
            - type: string
            - type: "null"
          title: Remote Archive Path
        hpc_run:
          anyOf:
            - $ref: "#/components/schemas/HpcRun"
            - type: "null"
      type: object
      required:
        - database_id
        - parca_dataset_request
      title: ParcaDataset
    ParcaDatasetRequest:
      properties:
        simulator_version:
          $ref: "#/components/schemas/SimulatorVersion"
        parca_config:
          additionalProperties:
            anyOf:
              - type: integer
              - type: number
              - type: string
          type: object
          title: Parca Config
      type: object
      required:
        - simulator_version
        - parca_config
      title: ParcaDatasetRequest
    Settings:
      properties:
        storage_bucket:
          type: string
          title: Storage Bucket
          default: files.biosimulations.dev
        storage_endpoint_url:
          type: string
          title: Storage Endpoint Url
          default: https://storage.googleapis.com
        storage_region:
          type: string
          title: Storage Region
          default: us-east4
        storage_tensorstore_driver:
          type: string
          enum:
            - zarr
            - n5
            - zarr3
          title: Storage Tensorstore Driver
          default: zarr3
        storage_tensorstore_kvstore_driver:
          type: string
          enum:
            - file
            - s3
            - gcs
          title: Storage Tensorstore Kvstore Driver
          default: gcs
        temporal_service_url:
          type: string
          title: Temporal Service Url
          default: localhost:7233
        storage_local_cache_dir:
          type: string
          title: Storage Local Cache Dir
          default: ./local_cache
        storage_gcs_credentials_file:
          type: string
          title: Storage Gcs Credentials File
          default: ""
        mongodb_uri:
          type: string
          title: Mongodb Uri
          default: mongodb://localhost:27017
        mongodb_database:
          type: string
          title: Mongodb Database
          default: biosimulations
        mongodb_collection_omex:
          type: string
          title: Mongodb Collection Omex
          default: BiosimOmex
        mongodb_collection_sims:
          type: string
          title: Mongodb Collection Sims
          default: BiosimSims
        mongodb_collection_compare:
          type: string
          title: Mongodb Collection Compare
          default: BiosimCompare
        postgres_user:
          type: string
          title: Postgres User
          default: <USER>
        postgres_password:
          type: string
          title: Postgres Password
          default: <PASSWORD>
        postgres_database:
          type: string
          title: Postgres Database
          default: sms
        postgres_host:
          type: string
          title: Postgres Host
          default: localhost
        postgres_port:
          type: integer
          title: Postgres Port
          default: 5432
        postgres_pool_size:
          type: integer
          title: Postgres Pool Size
          default: 10
        postgres_max_overflow:
          type: integer
          title: Postgres Max Overflow
          default: 5
        postgres_pool_timeout:
          type: integer
          title: Postgres Pool Timeout
          default: 30
        postgres_pool_recycle:
          type: integer
          title: Postgres Pool Recycle
          default: 1800
        slurm_submit_host:
          type: string
          title: Slurm Submit Host
          default: ""
        slurm_submit_user:
          type: string
          title: Slurm Submit User
          default: ""
        slurm_submit_key_path:
          type: string
          title: Slurm Submit Key Path
          default: ""
        slurm_partition:
          type: string
          title: Slurm Partition
          default: ""
        slurm_node_list:
          type: string
          title: Slurm Node List
          default: ""
        slurm_qos:
          type: string
          title: Slurm Qos
          default: ""
        slurm_log_base_path:
          type: string
          title: Slurm Log Base Path
          default: ""
        hpc_image_base_path:
          type: string
          title: Hpc Image Base Path
          default: ""
        hpc_parca_base_path:
          type: string
          title: Hpc Parca Base Path
          default: ""
        hpc_repo_base_path:
          type: string
          title: Hpc Repo Base Path
          default: ""
        hpc_sim_base_path:
          type: string
          title: Hpc Sim Base Path
          default: ""
      additionalProperties: false
      type: object
      title: Settings
    SimulatorVersion:
      properties:
        database_id:
          type: integer
          title: Database Id
        git_commit_hash:
          type: string
          title: Git Commit Hash
        git_repo_url:
          type: string
          title: Git Repo Url
          default: https://github.com/CovertLab/vEcoli
        git_branch:
          type: string
          title: Git Branch
          default: master
      type: object
      required:
        - database_id
      title: SimulatorVersion
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
