apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-known-hosts
data:
  known_hosts: |
    login-node.pcs.internal ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGyJHz2d91QWJ0ulCnmFt2OK/NR3fSyMbBgPWxZMmUZ5ty2m6bP8lSKHngwOHNXCVFjdMxtJFfNnUid75TEh7+A=
    login-node.pcs.internal ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDGT/PhrCHooofXh594zBfP5knjRv1sTWgyoe3Qlisiv
    login-node.pcs.internal ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCnxZ5MgdJgvIj5fD6Qbi49ZVM12qpcC3hu+r9nlHeCirf13wgBhHaNfqFNLdxanpLlt6zHgh89kOuqV6fw1DjedIb+1508l9BpLx4+ADWyCTmMwc9r7a5+eKQOWftxAHS1S1E/NgVQJPMG4N9iitcXs53+PoGo8AUs0Mj9Z9deUam0xSKcG8ayo9IzSPFG7cmgOju1dgYbG7TrZezgV5XCqqjBN6BRQcQz2HNYVWZrliFNydWEjCLdWc8JE3tRVYyxkS1iQI/+ImplcwwHG8CSTAs76KcdQaj45+P1SntZ2tui0jvi+tu2hoSndqhjGxalvHFeICtYTGyEL/giWjjX
