apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-known-hosts
data:
  known_hosts: |
    login-node.pcs.internal ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFXc9TQ7eYto4ExmtHZgfCckJ/ilsiBHbDzhWlVRBBaaW/70ThpK8Krccn1fYilS2LKo6h0vIB0Z8W51pIcE3rY=
    login-node.pcs.internal ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOHaTR5jGMOhO2TPHvccKT2PXtjCPFSDWn/L5XxYbdcr
    login-node.pcs.internal ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDMzkNwSy33Gz6B28C6txJ7AuFDlC2YvccLOvzgSygWUkEQ0Fg//s4es6W1zJmnEHMGeMn85TWuAVMUa3UNraV97febRImjcjKIAsEoKtAiVy+QkAljYIXdxZ1BT4zu+EQ8Q9SZ3UfA6C8sbUX/3n0hxzrsd6vUmwRZwrkBZEjxR5Urfy8xWYqp2XT1gQg5fc6vNMOOM9dRGYkwIUxc0bAqgQD1v/T09jB6bD+vtzUXAJZ4mp/uQ8B838/QdAKGiPIp8hbuGybDbwQvnawo7YULcb7nd6hhvz12GyLBnhYVttbUY+jFTRG9FVBghRqATu5KZCBagbp6h0Dz9Xq0yyOD
