apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-known-hosts
data:
  known_hosts: |
    login-node.pcs.internal ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBG8+cF9cXO7PbX0h8GkCH4iRMGSauQJ7J4Xd/5RQ03CHkL3EVjpVT0wPk3sGE/LzBLTBtTiibzfkL+9zm+ZU+l0= 
    login-node.pcs.internal ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDU8nKmXWjfoEJ37e69f3lRnYzjHDOeqtPW56nValKIM 
    login-node.pcs.internal ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5TGf+LWQ0qf61+UA/LF1a4/rdAOPbB8eN3qcpJT0fydrBhGBSNKh9rXsga1ZRt/l5+D6WQUxa3lnRng/F2oui8Zho38jGAPtmMQKbf/xQ/zD4LyuGIFRk8ojphaaZo82RPbCsMqIdQQ5bK6eM7zRxdKSaVb+pQIJnWKz4SV4dDIBY0wl76WRYYZ7loJXN5Xnm2S34lCipc3hvdWqMxbiTkZ2SCmB3Gu9MCWRp784S/wu4dZRNRzR5dkbcfuehtnLtkgtITJgzWjOc170K8e+FZMEyL6LAfhLGlg5mmiZMbdptAJQia/45aZymVJbKnQv7yeUrc8fG7X7nF7+047Vt 
