apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pcs-root-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fsx-sc-static
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-03b371715d79afb5e
    volumeAttributes:
      # Use IP address instead of DNS name - Lustre client requires IP for NID
      dnsname: 10.99.32.14
      mountname: icxs3bev
