---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: sms-api-stanford-test
spec:
  encryptedData:
    .dockerconfigjson: AgBlx6bMFaBh4vwkXDZU+GvZ4MPMo3GYOAJXJAZZqxPfFjMWzdKbttSFJUOLk7FOdF13zvYN7yJjK4D05UHeOe5MjCl5cXiCaBIH3DF4fTpynMs48LG31teEDw+JtOIOEXlD/TLRv3OkXG2Q5Nqko+Z3Z5EnVi+y6EA0TrxOmqnSD0rUit+B52+YMf1tbhLZGMHzPsLmcBbZbnmu5RAl9noz8S46pdf9dTXOFD3oEoBPWsz0cKpMvQGiB7EHY59077xbB4VMw4k1bM25nzDaJMBlz7miO955NkTrFI0nq6RzU/5khuoeLN5mSi1+wvCNo+Bjv6BliVBwDNjDP/jeunBjU5Ltq72Hvslg00DMyZoxovQNuVVkInf5HzBxYG1PCLNJdC66ZYhw7koi0hsdlhxZ5iK/KdeDskK3y6Dazs3qKxI5BwXmLe76gvGR1bzmkJDUweUdb4OZFxHOaB9bCInYju8czMZhOYB13sLt9mDWoN19Kr06xkHy7NbYIZlK1Z41qpvbyCQ/TqbuYSkU+CFlwdaMkZdsF+ECSOg4Aw39hobSZ1ADz0/PxA+R/3xBL2+Y9LvHdq+jMQIOrwU91mjmIhP6yunKFuvKL8gMI/aJHjKNhpDmgRS7w1dIqA1kRoUklalrjbDDBTDbtwhTHF6q6GbjjmCMmiQTfrbkwM61LRiMT69RSfpoA0HhHXiuspF/7XEKc9TeMAOSqFgROnrxhTOb61UnAMzpHVw5X4E78ABLPDHpjfbUqjQKoVtm9wywt6zq1g/eulDKeTvg/ZosmPUxEfRjpUpZeEwSThIryZm5BbvDupH4hAjkTzSVouJm3uxo6w5kQLH5r2VVEBnhSpdqMUXMK4Ze5TLpkjGgnlzfU2hCZtXBb3F8Fz0hxouHaTc5jLEpQ2gvm+1E3nSv/xWhXi0vldhSlYc/3NZ7IAphz6q4H1RqO1IZb+5vlHMbSAK5rdy88mmYWw==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: sms-api-stanford-test
    type: kubernetes.io/dockerconfigjson
