---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: sms-api-stanford-test
spec:
  encryptedData:
    .dockerconfigjson: AgAaxQ9xUuIUPk8kqnaqwYRJqnKSq0FH00xZvDSsYuQUPkz7nBIQSobUOvzKYl9YngzkW88vACyEig3TeYDKpsxXYizexiYBSec7BXMR9z39wZwtCBF7IpVM6QuuXOzx3Betva2KmxiMhSSlsgkrFu7HvUidECsg/Jbb0AapOkptW4xcREXFaX6DVnqe/6JICbzkMJMsdp9jDO6SesiZ1nD3JWe8z4OLrT2nszCbaQGz+Wj62CNNglesN9nD9IYbPrNSx7K0Y9rro9A46ntnAak12PQ6lO6o+amLXM03EKW0vcfgzvRMspfJaDVM2vXsbrrik8VjTNDABwzy+aFalA1YDfoUTTfHg7dCKt7oiaJEYIV+/vgw63viBOgXjEoj1xyQ6We7NACzLHg44yX9Sh9hr3dr/DIQn6hOUAA5KdIDe+d+lCC4a1HDvin8dIbZDZayMvNKbklxdbTpUOEvDzL+C/rzKGsY9pwatNow4ixzlYyMKTAuDhELu2m1QXnJwMsRnWoBDICUBtFKaDPAecmFTpt5IvCegdFlw6xsP8x8InEgzcXQj+k4KVSMNSZWqDiUL3WMhxnusHcmScNfsdTg2+/pI6r21P8O8/aaTOPfoqLvC458joldQEeBZ3KxAbQzoVRPOT5yUxRUdsGeVO+sMDRJX3hPDLtVPfiCDrfCgYLpS+OvymKHl0nyddh4DO1faw9TooPZGoEJa9e3mUuY/uPDtmJht6MvTMTeHE0wcYrJh3yd4onYi0jK+xwd9jzRWp9snIC+uwwZBqh2fIFYM+kmcROLc0IpYkpXPgDERqwpX7sMRDcF1/3gE18ytnMLa4jG17NdL2MbcJXGA3Vn1JqjUqmwCAqBTaZrWozIPfXq7/AM1Eo386SX5HW7vZ64KK4z7NuGQSKuxCnDj8QG8lu6LVJn6g3lUTe9hvMj/J8uZwZD6r9mFVWL8NC3ttTq90mSLzRcdg536Q==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: sms-api-stanford-test
    type: kubernetes.io/dockerconfigjson
