---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: sms-api-stanford-test
spec:
  encryptedData:
    .dockerconfigjson: AgBinTnGD4wch94DhprmkU0yqCptzvFrtTMu3QGy8lF2lmdgOpgtfUpNvZoGMiVz0Bh1hJ7CWpdsvSX7eDZ6YeKFpHv9m4b7dxIw3Z16uj7EosimZhlPAgZwhFQrBT8WcWGOtMCZZrMZnq0k/rCLNl1HzcHLV1HPPp0hOhUhp99QFQNkwJysy+3ugS3k9vnYBebsu7lJ7zqNyBVQ62ZuvisXDtcrUfC1/Z9O8Y6Ma8AI8BL7AmM/nZp4ys8OWVaVt83zoiqC73XYWiMH7FHQu+zbudrM9qNm6cb6+8b1QAaj2AAWsm28a73EqUMPXRwfZDPpw3Ud0sQybQQkaT6sN6nbfikMvDE9pq583C1Cm7P9WpuG2YPbQgeWDdZweVPjEpFiFVm+zPIhlWyX/yemLKeI2UtE2TcVM3LRSTje3YdU0nP431bso8zKjZfhv7drJmiZfSThUQNrym/8lIgGpqeUqKXIQaU9uv4muwibTufCjLwuQjvfAR6qUjoILeScTOfVrCunxOFjMfePUvMOC/W2WCB8JI4UOirML/1ZWNc1CnOT7RUZH0PWp3Kbqi2mHfhJ4kq4piMarK32PndNJWKIYKGeQEWyCQHdmJsQqdKV1DxVIjMHObywlwjSQb2z0OgrxtlDXCE+oegR3HduJ2nzdXjUhku5LH2WjZ7DKdGUP5lZJunGR4RmDp/DPxMAlrpgH7wZnCb8Conp2MssYXyzf7iQCYgYW00Cw3ZnECLpO+L5nfpCyA+NQHFOvEMAos3I1i8X9AE1x2h/mqQtFJ33ofoA3pTy7DiwU2e2gXIwN1YpiLMLsmKi63+J1TeFkYqxnUS2cWALsUwmCoxwE4bPxb9qCKSXpEpQPdl0kgKHwVUW6VMqAnoeFpHZFJrA1zLIkp/m5PaiLW+f1mH9lr1repX42kaqpZECFPA5bULutlpKNkAhw733HJ74wqdhI8ro9fiYpf9TWkmBsA==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: sms-api-stanford-test
    type: kubernetes.io/dockerconfigjson
