apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sms-api-local

components:
  - ../sms-api-local/images.yaml

resources:
  - alembic-job.yaml
  - ../sms-api-local/secret-shared.yaml
