# coding: utf-8

"""
    sms-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from sms_api.api.client.models.simulator_version import SimulatorVersion
from sms_api.api.client.models.variant_config_value_value import VariantConfigValueValue
from typing import Optional, Set
from typing_extensions import Self

class AntibioticSimulationRequest(BaseModel):
    """
    AntibioticSimulationRequest
    """ # noqa: E501
    simulator: SimulatorVersion
    parca_dataset_id: StrictInt
    variant_config: Dict[str, Dict[str, VariantConfigValueValue]]
    antibiotics_config: Optional[Dict[str, Dict[str, VariantConfigValueValue]]] = None
    __properties: ClassVar[List[str]] = ["simulator", "parca_dataset_id", "variant_config", "antibiotics_config"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AntibioticSimulationRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of simulator
        if self.simulator:
            _dict['simulator'] = self.simulator.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in variant_config (dict)
        _field_dict = {}
        if self.variant_config:
            for _key_variant_config in self.variant_config:
                if self.variant_config[_key_variant_config]:
                    _field_dict[_key_variant_config] = self.variant_config[_key_variant_config].to_dict()
            _dict['variant_config'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in antibiotics_config (dict)
        _field_dict = {}
        if self.antibiotics_config:
            for _key_antibiotics_config in self.antibiotics_config:
                if self.antibiotics_config[_key_antibiotics_config]:
                    _field_dict[_key_antibiotics_config] = self.antibiotics_config[_key_antibiotics_config].to_dict()
            _dict['antibiotics_config'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AntibioticSimulationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "simulator": SimulatorVersion.from_dict(obj["simulator"]) if obj.get("simulator") is not None else None,
            "parca_dataset_id": obj.get("parca_dataset_id"),
            "variant_config": dict(
                (_k, dict(
                    (_ik, VariantConfigValueValue.from_dict(_iv))
                        for _ik, _iv in _v.items()
                    )
                    if _v is not None
                    else None
                )
                for _k, _v in obj.get("variant_config").items()
            )
            if obj.get("variant_config") is not None
            else None,
            "antibiotics_config": dict(
                (_k, dict(
                    (_ik, VariantConfigValueValue.from_dict(_iv))
                        for _ik, _iv in _v.items()
                    )
                    if _v is not None
                    else None
                )
                for _k, _v in obj.get("antibiotics_config").items()
            )
            if obj.get("antibiotics_config") is not None
            else None
        })
        return _obj
