# coding: utf-8

"""
    sms-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sms_api.api.client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_check_health_health_get(self) -> None:
        """Test case for check_health_health_get

        Check Health
        """
        pass

    def test_get_version_version_get(self) -> None:
        """Test case for get_version_version_get

        Get Version
        """
        pass

    def test_home_get(self) -> None:
        """Test case for home_get

        Home
        """
        pass


if __name__ == '__main__':
    unittest.main()
