"""
sms-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.2.2
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from sms_api.api.client.models.ecoli_simulation_request import EcoliSimulationRequest


class TestEcoliSimulationRequest(unittest.TestCase):
    """EcoliSimulationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EcoliSimulationRequest:
        """Test EcoliSimulationRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `EcoliSimulationRequest`
        """
        model = EcoliSimulationRequest()
        if include_optional:
            return EcoliSimulationRequest(
                simulator = sms_api.api.client.models.simulator_version.SimulatorVersion(
                    database_id = 56,
                    git_commit_hash = '',
                    git_repo_url = 'https://github.com/CovertLab/vEcoli',
                    git_branch = 'master', ),
                parca_dataset_id = 56,
                variant_config = {
                    'key' : {
                        'key' : null
                        }
                    },
                total_time = 1.337
            )
        else:
            return EcoliSimulationRequest(
                simulator = sms_api.api.client.models.simulator_version.SimulatorVersion(
                    database_id = 56,
                    git_commit_hash = '',
                    git_repo_url = 'https://github.com/CovertLab/vEcoli',
                    git_branch = 'master', ),
                parca_dataset_id = 56,
                variant_config = {
                    'key' : {
                        'key' : null
                        }
                    },
        )
        """

    def testEcoliSimulationRequest(self):
        """Test EcoliSimulationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
