"""
sms-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.2.2
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from sms_api.api.client.models.variant_config_value_value import VariantConfigValueValue


class TestVariantConfigValueValue(unittest.TestCase):
    """VariantConfigValueValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VariantConfigValueValue:
        """Test VariantConfigValueValue
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `VariantConfigValueValue`
        """
        model = VariantConfigValueValue()
        if include_optional:
            return VariantConfigValueValue(
            )
        else:
            return VariantConfigValueValue(
        )
        """

    def testVariantConfigValueValue(self):
        """Test VariantConfigValueValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
