"""
sms-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.2.2
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from sms_api.api.client.models.simulator_version import SimulatorVersion


class TestSimulatorVersion(unittest.TestCase):
    """SimulatorVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SimulatorVersion:
        """Test SimulatorVersion
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SimulatorVersion`
        """
        model = SimulatorVersion()
        if include_optional:
            return SimulatorVersion(
                database_id = 56,
                git_commit_hash = '',
                git_repo_url = 'https://github.com/CovertLab/vEcoli',
                git_branch = 'master'
            )
        else:
            return SimulatorVersion(
                database_id = 56,
        )
        """

    def testSimulatorVersion(self):
        """Test SimulatorVersion"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
