# coding: utf-8

"""
    sms-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sms_api.api.client.models.simulator import Simulator

class TestSimulator(unittest.TestCase):
    """Simulator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Simulator:
        """Test Simulator
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Simulator`
        """
        model = Simulator()
        if include_optional:
            return Simulator(
                git_commit_hash = '',
                git_repo_url = 'https://github.com/vivarium-collective/vEcoli',
                git_branch = 'messages'
            )
        else:
            return Simulator(
                git_commit_hash = '',
        )
        """

    def testSimulator(self):
        """Test Simulator"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
