# coding: utf-8

"""
    sms-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sms_api.api.client.models.worker_event import WorkerEvent

class TestWorkerEvent(unittest.TestCase):
    """WorkerEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkerEvent:
        """Test WorkerEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkerEvent`
        """
        model = WorkerEvent()
        if include_optional:
            return WorkerEvent(
                database_id = 56,
                created_at = '',
                hpcrun_id = 56,
                sequence_number = 56,
                sim_data = [
                    [
                        null
                        ]
                    ],
                global_time = 1.337,
                error_message = ''
            )
        else:
            return WorkerEvent(
                hpcrun_id = 56,
                sequence_number = 56,
                sim_data = [
                    [
                        null
                        ]
                    ],
        )
        """

    def testWorkerEvent(self):
        """Test WorkerEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
