# coding: utf-8

"""
    sms-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sms_api.api.client.models.antibiotic_simulation_request import AntibioticSimulationRequest

class TestAntibioticSimulationRequest(unittest.TestCase):
    """AntibioticSimulationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AntibioticSimulationRequest:
        """Test AntibioticSimulationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AntibioticSimulationRequest`
        """
        model = AntibioticSimulationRequest()
        if include_optional:
            return AntibioticSimulationRequest(
                simulator = sms_api.api.client.models.simulator_version.SimulatorVersion(
                    git_commit_hash = '',
                    git_repo_url = 'https://github.com/vivarium-collective/vEcoli',
                    git_branch = 'messages',
                    database_id = 56,
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                parca_dataset_id = 56,
                variant_config = {
                    'key' : {
                        'key' : null
                        }
                    },
                antibiotics_config = {
                    'key' : {
                        'key' : null
                        }
                    }
            )
        else:
            return AntibioticSimulationRequest(
                simulator = sms_api.api.client.models.simulator_version.SimulatorVersion(
                    git_commit_hash = '',
                    git_repo_url = 'https://github.com/vivarium-collective/vEcoli',
                    git_branch = 'messages',
                    database_id = 56,
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                parca_dataset_id = 56,
                variant_config = {
                    'key' : {
                        'key' : null
                        }
                    },
        )
        """

    def testAntibioticSimulationRequest(self):
        """Test AntibioticSimulationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
