# coding: utf-8

"""
    sms-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sms_api.api.client.models.antibiotic_simulation import AntibioticSimulation

class TestAntibioticSimulation(unittest.TestCase):
    """AntibioticSimulation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AntibioticSimulation:
        """Test AntibioticSimulation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AntibioticSimulation`
        """
        model = AntibioticSimulation()
        if include_optional:
            return AntibioticSimulation(
                database_id = 56,
                sim_request = sms_api.api.client.models.antibiotic_simulation_request.AntibioticSimulationRequest(
                    simulator = sms_api.api.client.models.simulator_version.SimulatorVersion(
                        git_commit_hash = '',
                        git_repo_url = 'https://github.com/vivarium-collective/vEcoli',
                        git_branch = 'messages',
                        database_id = 56,
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                    parca_dataset_id = 56,
                    variant_config = {
                        'key' : {
                            'key' : null
                            }
                        },
                    antibiotics_config = {
                        'key' : {
                            'key' : null
                            }
                        }, ),
                slurmjob_id = 56
            )
        else:
            return AntibioticSimulation(
                database_id = 56,
                sim_request = sms_api.api.client.models.antibiotic_simulation_request.AntibioticSimulationRequest(
                    simulator = sms_api.api.client.models.simulator_version.SimulatorVersion(
                        git_commit_hash = '',
                        git_repo_url = 'https://github.com/vivarium-collective/vEcoli',
                        git_branch = 'messages',
                        database_id = 56,
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                    parca_dataset_id = 56,
                    variant_config = {
                        'key' : {
                            'key' : null
                            }
                        },
                    antibiotics_config = {
                        'key' : {
                            'key' : null
                            }
                        }, ),
        )
        """

    def testAntibioticSimulation(self):
        """Test AntibioticSimulation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
