# coding: utf-8

"""
    sms-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sms_api.api.client.api.simulations_api import SimulationsApi


class TestSimulationsApi(unittest.TestCase):
    """SimulationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SimulationsApi()

    def tearDown(self) -> None:
        pass

    def test_calculate_parameters(self) -> None:
        """Test case for calculate_parameters

        Run a parameter calculation
        """
        pass

    def test_get_results(self) -> None:
        """Test case for get_results

        Get Results
        """
        pass

    def test_get_simulator_version(self) -> None:
        """Test case for get_simulator_version

        get the list of available simulator versions
        """
        pass

    def test_insert_simulator_version(self) -> None:
        """Test case for insert_simulator_version

        Upload a new simulator (vEcoli) version.
        """
        pass

    def test_run_simulation(self) -> None:
        """Test case for run_simulation

        Run a single vEcoli simulation with given parameter overrides
        """
        pass

    def test_submit_simulation(self) -> None:
        """Test case for submit_simulation

        Submit to the db a single vEcoli simulation with given parameter overrides.
        """
        pass


if __name__ == '__main__':
    unittest.main()
