# coding: utf-8

"""
    sms-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sms_api.api.client.api.simulators_api import SimulatorsApi


class TestSimulatorsApi(unittest.TestCase):
    """SimulatorsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SimulatorsApi()

    def tearDown(self) -> None:
        pass

    def test_get_core_simulator_version(self) -> None:
        """Test case for get_core_simulator_version

        get the list of available simulator versions
        """
        pass

    def test_insert_core_simulator_version(self) -> None:
        """Test case for insert_core_simulator_version

        Upload a new simulator (vEcoli) version.
        """
        pass

    def test_latest_simulator_hash(self) -> None:
        """Test case for latest_simulator_hash

        Get Latest Simulator
        """
        pass


if __name__ == '__main__':
    unittest.main()
