# coding: utf-8

"""
    sms-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sms_api.api.client.api.simulations_api import SimulationsApi


class TestSimulationsApi(unittest.TestCase):
    """SimulationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SimulationsApi()

    def tearDown(self) -> None:
        pass

    def test_get_antibiotics_simulator_versions(self) -> None:
        """Test case for get_antibiotics_simulator_versions

        Run Antibiotics
        """
        pass

    def test_get_simulation_results(self) -> None:
        """Test case for get_simulation_results

        Get Results
        """
        pass

    def test_get_simulation_status(self) -> None:
        """Test case for get_simulation_status

        Get Simulation Status
        """
        pass

    def test_run_parca(self) -> None:
        """Test case for run_parca

        Run a parameter calculation
        """
        pass

    def test_run_simulation(self) -> None:
        """Test case for run_simulation

        Run Vecoli Simulation
        """
        pass

    def test_submit_simulation(self) -> None:
        """Test case for submit_simulation

        Submit to the db a single vEcoli simulation with given parameter overrides.
        """
        pass


if __name__ == '__main__':
    unittest.main()
