apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-cache-pvc
  labels:
    app: api
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 2Gi
