apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-sqlite-pvc
  labels:
    app: api
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-retain
  resources:
    requests:
      storage: 10Gi
