---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: sms-api-eks
spec:
  encryptedData:
    .dockerconfigjson: AgB6jIxryAq99Bz3H9aWzdpNU6xxpiyWPm+PB6JJXrQGiJab1juR5njZePbx0UFKb4ZP0SUdMVxdJQtykrlixD87ndAVS9eDUQqsJojL8YT6jGE4S7EpcPIBs+B/aNB9wPckryRHeZnuwwUl0ahcFkFraT2bgh0E4i4wvaf22V1sqqpU/+honQlAHB5QfAYFJ+6o1fuSrHKxCYM5zPY0jnW8zpu8zuDKBlvrP/fRiA7eCCCS9ZRYQe0jqgNzi3XwPy1di9svIZtQPq75JCzitG5QwMv/iUUp2zRnYOmEMKKj0peSHKqLz6u/KBoFLUjsm2AgZM6Kgh65ZwXT9+FZZCCioq8fu3EWnQo05pnUxIket9a7Omd/lksUB1lvOSuziZpUvZHiLmvZUth6iyrfEci4uk5VLLr97t4swQd6p5Jvpe3yCFPnIMvf1K9bxJwRpIeOK9FlHxiPnO5EUoXhH9rvOZLyKG0WEaV9EnCa5Z/mud+jTP3hzgVM0/Hyp9bhaBYJf5Njnh53rIgxPUDPOAObJQpr+O4hxitJIS1T/7LqVBRIgimM74/zu8BZXV4eV+DFmrAgpzsGqeY1iLRs+3FmeSMNpFpundgs3XXOG71cYna30b/VIUgss7x30E/lctw2NoV1NCvHA+bXjZBHmGFFkdEtCZZqWRCcTcw2F5uISKhVSavXO3l8ze/EQc5lEPZOH0c9xcLiBWF6mDKrF948/JE34oYM+2nWG+ullInyEBi00uwNDP+slFbZV+y7qwxKNYLJ8081q7Tz/Ug5ujeHXHesGsrTam8Fthl20Ea9ucZMweOo3sLGvpgstfoCTpYnKQiTOeKm3Cv2yjl2cWckUGrj12NUzZ8yoKiT0px+gYMC6SE5nEy12jcFnK4tOs0muTa0S4A2kYPpw3/u58ojGHKdDRIdiBzxZhSwZvrq2JEnJJjaOTdRZzNDljn8RJxcQMYUBhyG3cX+xw==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: sms-api-eks
    type: kubernetes.io/dockerconfigjson
