---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: sms-api-eks
spec:
  encryptedData:
    .dockerconfigjson: AgA9pQWPZUcJI1iWJKqTg6TV/LK/fOn+a8jNN8UBBRoYjT3LyX0ffDltbssn/kLKevdiITdWaXa1jwaQPmhiBgm39qKkK1JBgT75hNLqvpvy9rvwS+/QUJlFmtTn6Yq3mBfITfQq+PxtUJC6sFSrg/VDYWkYWHZBwPnHCmU+aFa9XQgVffP3YiapiLqowEks4hPfV6MGGUYfWMoMJXyBGejIbLU+gmp+tmU5IbChQdaVhpkZ4wNAp/PA2AsLIK9oG9gvCNflUPJzfGj3TExwERs9f86uMwrf5nm4lBGlmi0iPiITbZPY2aaApoGlj0OF54Hq3o4pyYAv8Qwnr7m9Dv4tZVR520JT8V5whMBXzR4SK76TW5kCp2kvfzFTbxqgUt7NAR7nKA2wIm1ln8ktt2yoxdzNXIHexnydAfX0lca7xYeWZ71wE16Mnn8f2r/HKbjekioUdLEyWkGNUhzoPB57ZoDznWmiIq3IN96UX5DrEUro8xVNLLFJiecfNcTUtWUsMYt17QW7YhKlSHpgWNscjCjOaGTe6ZbYwuRDVtBQz7S6Bl1Z9G17U7dcRJxu82lbTRihPatbQBvY9B25barphJp1HqHVQUtD/Cb74aISOX9RxSBbkIrNUd7yQQC4Gn6rgK6dnMRsR650biCguwn35Jm4HDASBemEaYg4BMpQrA8YhnQPGoPO67uJ/rLQXB04DmefHblgiouFSDGcFWkfieEpOBtkFq2nxXQCmfP+tTsXjvzCjjmR74lw8RI+jSZVrNLZVn970C/Pt98hVyW6iJoVivwKaF0bnrBkpayCerR6maIROaxVt4LHZcvV2dES2nJgwBvi9Wqr7wIQyPT3Hz241f5SK+iBRof7MBajxwAkkEuJzzqrQt3dRZbnoNUsJ/fWbbo39iZSX4Fgia+As3BabMkKxTxnzjaAClQgxQb1wNdx5ntpgn45K3AhvIJvedDMU69FO6mEYIrxFerS
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: sms-api-eks
    type: kubernetes.io/dockerconfigjson
