apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vivarium-home-pvc
  labels:
    app: api
#    this is a fake volume not mounted to HPC.
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 20Gi
