apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vivarium-home-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-static
  resources:
    requests:
      storage: 100Gi
  volumeName: efs-pcs-root-pv
