---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: sms-api-stanford
spec:
  encryptedData:
    .dockerconfigjson: AgAKEXXfVOVkbDp7MFallWhLmd6zVPMMyjwwOGOcH9/PIepBeXLBeck6VYgSziKVgB8152ItbB1To6lREi2gKHqUnZyw/2McljmTvo+X6HnRooh4blcVD3TRadOIL7DBm9RzANBmA0We/Vwg71R0wA1iqWze1gUyvukI65qWQsJk4sYqGyXUeY7NNnjIZRCOT6TOOrXzaLnllxpP+r+MgIAH6GhjsYWEptHsG7ZS7X07DzOU1SRo1X+1PM5D9Wi+swY2T+aRD4saO+z4VuxPvzbWE0nw3fCxSGc5eMSweuBB3gCMhvW5KYuSoPy0t8XvbeWHOXtM9wz7GGB7+pOMgPnWx5RjPyGwf5SFo2eNieF2mavcikInk28rRdaXmiZUKDb2qxHOTZDopcZOC/qMqRyGSId1kUVYOGmRF4x8Fsi/KX3SFa/jMUXGMX+y5JrdcoNjxdO3oekufd/DfF2wkEmfQP6vnl9MvdnMXFlk5TnEAAY+nyMbTJVpvkLcRMdcx4b3lkfTTaI97nrRCheSwEkw6H2m0+j49jtVoMew9/CBfMs/kKAEPf1b6vejZa2MHfHbHXZp+UtpqDWd7DlikbwQ+cNFE8VS76+X1sFwyBsrjbm4jCo9DqXqrlfLsrg1eRpheGtn8+sK1XkkNvAMLPJU4APrLQuWhmHwm+ct64MQIHyImbQ4m1YOYllwITPFqcomXWCs1t4rPx1+O0v3vejVswm06UvVozdtyutTog8qC9wWWSBLv0aWWIkHCgZhzvSueQ2jRWRZ2Af+2/+zJQ5b5NvBZehkrye8Flq05h3PwRxZmXL5zo4LFblHR+VW4sJmGWGykLBqOoDM6+9rujnBnwc2c+A2yHFulGNV72cub+la7+Er28+k9sB9IccPosK8I7ELojbElYcRTANEClua+8qlZ031L8QqNkz6/BMRov+dDHA77gIdeLlNZZcfiI1FUPfvgM0/Uy5eaw==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: sms-api-stanford
    type: kubernetes.io/dockerconfigjson
