---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: sms-api-stanford-test
spec:
  encryptedData:
    .dockerconfigjson: AgAxloOQcnHQWcjUsr8Dx7fVhmWA/AJI6md6jceQ8sbawKLF93g/4YVSJSSFIVokZm7jWcUv696kLW/fJ2tXUcqZWVXaxBviM4JPZji39dFY03kfMCWFrrn3DAeIuIZQ/Y+Cm4OM16AiGterc7mXSY6lxCdBnaS0oEhaqk3zYHUDguN5M7UbodaNTaXAhwH1qm4bWJdTXrjeiYjPYl2SaFxaQ60n0qGwcpMyTweo49izk51nA68yo3OV35V7ta9iJePKsCIX/fRyTUnpa8PYgq5Qlcu0mnu/6lmLn99sKlbNO5TugxHCT4S5gwUJ07IRWQ8YErFq462LLMSRueahJGDCNKjKacL3X6el04pqnfCwgNWy5ls0BYfhyWhHkEpAHfpQN4jSL42s63aTD1aQ47PX+SWsVOcad8rS9wMDe3j2R3tZaTHD7VPiwkAr5+JrHP14jcuLxiVHWZOUD2t7AKyF9ZUdAjDLc+pcrB3UaYorqrO9qKVpeRWI5g34Q+h2IM57QeD3VxZYk72AukQZGgK9lpVIJNtykRJyDM+C6dmCDMzO1RxJTl6iBOQzPYQ/pqI+zR/JpBu3BRtB6Dy0ze45dHNkbC85sXrSk+NcHcTY9wxJxVVt4wQ3Mp675MbKxz7ePP3tKF8lR9geAbQEP3IPc7XuxSAU4WwIOR1t0JxiH9+//uwVwidCPaa7isw0/CAsXQWtCH/WwouyN8np0NOv9K28JbncTIatAw8U748hZmBeyE/AOvZLXLA4QOzZeOp/CPR4uprc3pw8+FXDky5M6L2RzZqHr/Wqit+wcUTvReKgMgbF0LAa1ks4gCCUGl8+8vI80ml0vv8JMW/2NaDD+FRzVr8+xTQuUNW4NrUf0l2gNZ1KBS+izXcwUqG5VTHWwjoa1XyVFqpAleXi3Pr1wCIYFDCjKuR0KumPsRAk3RbDPaIfkYnJo+ry2fbNpQRYXnAybcBcRiCa5A==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: sms-api-stanford-test
    type: kubernetes.io/dockerconfigjson
