---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: sms-api-stanford-test
spec:
  encryptedData:
    .dockerconfigjson: AgAtCZA67o5HdyJkcev1anjYBlOkB2GVp3/WHY9a8lVJlDCB37j2uJHT4+0ZBoUePhX66hm7sPcVTJOtJPF+4m+lxRg1ayYxMdXUPn3zMGPh7gp0DP8K366JNmR/8uIYRLca0gYFkWbuGwvDoCtMKsFcGPS3nj3ieFQZaaLkFsTNgWBC6em/aKU+LA7kVw+QsgYzfmAtUIs46Qr57cUEqE394IywyysncOhrSOLMGTqbLtDOtZD0f0uCFNeXkfcUQNDb8uEvo2A1b99sBP1k75af5DKmvUQ+qCL+srMEnHprshsmuoxf2rYDQWkQcFIb7fE1zqwvkvyCiJ2aNFMHfeuxWHYbtFnLUioDjhGvbdm5eu7Vsuyg7/jhm2F0YOf9R8uw/eaNYm1RkHrAurOACarlU8XwOGf4MBFrMj7YPa0OTUTiiFgG6sri64/yTXumEvpgByub6/gobJwnAUewimfnaAq0auo9xfbmEEEXKzALbYsB7Ml3U8NgXHOlN0rgQ2kjI7IRgxXN9XX/mCamfxp9fV9GJFhuqQYzRb2WfiROzBs8eyeXU+98T89GYydPeQxfZHsfl9k6160VF2WE8SPWkKVHKMpT25peSyYe4Vz0nKmbnb/G8T89cKPn6sozilYvXm6E1kYVgWlX4W7PJcEBjINsMxHymXbF6UAW+xUA7E94651NniMf24aDED2Vf/Y/E1aWMqOlRgIKJRoT6OY8dEQuE8+efOV9MCYpfDGhohdp6cFvzEndfYfzx11DCHPtDInCeRvYF6g2ShQnhSoD12bwXU4RjVFLCAULCrVdVD5ARU1A9JmKbYB5jH+6ENyNSG5O/Kn6NXv7cuI7l3tU3sPrtKKyNwhqb7HaI2VfGJTIOEzRvcJvZgmEJV3ma7fUBfhPqd/iQb70i8JJ62YQjyQExyx/JRHaz1tue4RUdNrWZXMmkPaHc7flawvakWthJCpAlQj57ATF4g==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: sms-api-stanford-test
    type: kubernetes.io/dockerconfigjson
