---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: sms-api-stanford-test
spec:
  encryptedData:
    .dockerconfigjson: AgC/SkgxeUmbPSM1QHCCYKB2a/tGRMbWD3INnXShAYyksAdnTIfDAOPksbfS+GGkaWKldgqAp440zEcu/fQmE7wCDkMQloXcvB5omEd++ujJbxa4K/8B7vKFDT3B7AZnidY2Xj5ZsE3mV1eAzH8KAidi247hFlLqCW7qC9X+kPzqhomxbS6AQfQ1oPcr1uK98FZZ78Rjyhz+MURoLLt7O0yHOPY4aPuCKgmrXImvf+/p2xhaWbnC0C7CVclDFxKHvEMLtA89ogztPq22+cpmsPoLOmsQCFMiNcYq2viIwZfi/wrc3maibu1i42wctx/oIbMzd5/ne6Y9/h/1KYrz+GMtA+KI2DkeN6QKeVfNgewDR28s2gnEEcabMSbEuBZ82/YbUe98iuZ/5I7pIxW5gVWZ3f5S18MurdQjIuRvMapMuevAnbI10i6sdgnc3PGRrwxYcSycYCLDahAMeW9BR4w8KRzIhrsq24MH1iSteZvRhPQkEM98QaOhgp/rgn73SnHkQDwbj4GZL6389rnIHqmAeL45PzN8GI2b1fcGgB2mHfcSn+b3lJn6zracWs6cmmHxAKZFakk5onExVzUOlQHHdwnmgOiL7g6M3T0s70KZO9+X//tR3MSHkT1e1QQ7YhFYFeyvxZ+kejVGgkSQ+BvKYCOlz6iF9f1k+zXEP/yE0h+iKpC8ZEvtBUaSDJ6v6V3/Ujb2BPxScuGRT93+Wdvdu/qulxWkbEoT2j6tcixPCDH2s057UPqa2agsTNYCNtUTZXY54wXv2znebAps//B+ruVuBuCIhutH31fz2DD95VEauPP1iWlUVR5AIsbm8o65p47rssrestgYh49qmJMGVPgu4tshgSeZNzplsON0d/eDn7Gym/gG0tIpTdS3QtNtLoySy/nHatITVbEyxgcBkKtwB0WyULHdyOtodAJBF+hHJUcboOuU2vNC1I9dNd/QK3Q75zcuQjl/RQ==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: sms-api-stanford-test
    type: kubernetes.io/dockerconfigjson
