---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: sms-api-eks
spec:
  encryptedData:
    .dockerconfigjson: AgBeaheCYbYy/xc8ZZnwdNNrMmli710qtCtdjtD4pYg+Ggs2ISVIGjUoLHNKyxqhTfCsDLcZ8MRhis+xaxoIZCAVhs7ksat0staLjMlrtw2pAhLiDBp8v3BQsLIjIgWB3a6QJwyMjBPS61r7lO/GJ54OzOywY1CeaQU3shNQXGpjmMI8r8BW6Eus7MMWoUtRvV/TS07RVB8T7sNqPL60hAdhzeVuskIYtwzplFWkyADkaH9boT3PvZ+1qPp05Ol6qpgg6B8Qds7+/8Bmo70mK30UOw6MHD8BKzp09JEzzY9Lf8JONot3lFHE/AkA8LOQQm3UBhqELY//MSmU4i+/Z+XyM6ou6jmtQUxqgdh2Vr1t2kqpeUxLa2MFx6wxUIqX0j8JY+PYB5jPefhiK9fUmTWusb0vZO8iFny+WZ4rm0sEV/4kksDtM6PHw/f5s5pqiPEVqsOqqA6uoAYJF4KlSz35f6o/btlprptImOOQeAQX/1WMfejitIJ5OWuE8btw0JyEfQc0cO2El+y1iIZym2yq6Mum4nC7WP49nIe0Oy6axHsoiPUGQ2lIEpHn0Zx8eEzAPyQdFXO2Wacam0XzYmLmxUoUkKcr8NV5LK4fkE0PHx4Jidp3urgGEdBBs8ousOZqN+lWJKUX6k30R+pnTl+pUT/hIIBv4K7CJHVbqecATCGiYIN2AYMpTeIeCkuEUzioJzXxKn571g5mGfhx6ObhFe+lupxlDsNddb073t60NpkBcLVOwTPsUAN6El74Y4/G6R1fzUrmpK5Rn0oasx6CRV+Mzbk/ymIOrUUF0in189Dgz9zNDcQZqLOmgvQ5WWTbFi4ol0AswEEJ0TWNEHQu1GK7DTb7D9BC3yw3D6Bj1hAfXOvZV2QRqKAj8h/Jj1sxBFkLvWn7Q1I9kmUEcgws3UbdLuJQuCORcLvPmRpqOP+W3MV0e1P8Dp48IFWgcr/PHpPNSi272e6SyX9eBKBy
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: sms-api-eks
    type: kubernetes.io/dockerconfigjson
