# TODO: finish this

FROM python:3.12.9-slim-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates make

ADD https://astral.sh/uv/install.sh /uv-installer.sh

RUN sh /uv-installer.sh && rm /uv-installer.sh

ENV PATH="/root/.local/bin/:$PATH"

WORKDIR /app

COPY . /app

RUN uv lock && uv sync --all-extras --frozen

EXPOSE 8080

CMD ["make", "gateway"]
