---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: sms-api-rke-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBjFU5FyIyRCNu4IVapdJmL4XuGeXhcgh681+VG6A6JI0u9iKVHBJe+Dg1oUZAdqAgeYVQDpCvo1YNVv+I5rrVg75g+MQRW0bj7pflM6K15O9sPhnMgqRVy3Q/BWyLoJd5sttYrX2VJIxriA2c4V+Lujfk7z1FnL66ORD0B6J1M1tGv/nDVAOc3dwJ+690vx7AYulKRPgUFjAWytSUcneI2/+d+gnh88eG3JVpVE1WpGa+fKVnep7outiV1we39XUSfEpVduK9Uphi4LyKjsOsI2Tw6aHdcCzI7ZVI9HpI2L/R5LKKUPwAX9nFTigdZImBla3NC2k3qXI9PvNTh7fSEyRaqQuBlMUiqZEZPdnbjq0Bn8uaZX5lchkwhJ10V8UEhEPx98nIOgfD5m73Wmo65u1Z5elu8cdxjSQoqkgWD7N7NqGhHxIG0fa8vyFtf95Oz6CqBa6k3bETGKav1LxBSes5V2Uf/5YVtw/gNey/6RRWbRfAt4bnOa767rXJNnAOhANcDTRDDyke8klGyC4KrFaZNGix51CdL55kuxaaKwprks2+LlGyYaCHB6rHWtVEZnyolsPKBBCN5D8ZcTLwtKhoHZlKSqoxtQyaC8k5wnepg5Q3hqgdyW4bpkjH96ANuB+9+okwBQbrUkl1527DmIA1aeSZZefKFjpulAgf0kUicIi8pM79LxdZebDGOyIEbqqBJl25VhTRXk4MoBezk/9YgmHsLovjbeJMR9vxMP79NxiJGIVIBEQ5IBoxFsJMhfOvOMooys2GZoq35Gt1D40uPmKiwyoMy3wDw6LOkcPUGtZAiWYmk6tIEZgNuN9joRZlyY8KbFIH8bj6MuJmrDO90+U2KFjKtnRjyqefSLpltDRmNBFcXzbUziuOgQ2ael1fm7zANBKKTo5JDMsUpBW8tC3mxg5H4GyVVTpKa0fTyn9/kensC7au+2YXOWXPhF5qXjeBtH5iQjuAnfqPL
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: sms-api-rke-dev
    type: kubernetes.io/dockerconfigjson
