########################################
# SMS API Server: Run Simulation Service
######################################## 

FROM python:3.12.9-slim-bookworm

# uv setup
RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates make git
ADD https://astral.sh/uv/install.sh /uv-installer.sh
RUN sh /uv-installer.sh && rm /uv-installer.sh
ENV PATH="/root/.local/bin/:$PATH"

WORKDIR /app
ADD . /app 
 
RUN uv venv \
    && uv sync

CMD ["make", "simulations"]


