apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/biosimulations/sms-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: api-config
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: postgres-password
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: postgres-database
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: postgres-host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: postgres-port
          volumeMounts:
            - name: api-cache-pvc
              mountPath: /app/scratch
      volumes:
        - name: api-cache-pvc
          persistentVolumeClaim:
            claimName: api-cache-pvc
      imagePullSecrets:
        - name: ghcr-secret

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
    - name: websocket
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: api
