apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      nodeSelector:
        vlan: internal
      securityContext:
        runAsUser: 17163
        runAsGroup: 10000
        fsGroup: 10000
      containers:
        - name: api
          image: ghcr.io/vivarium-collective/sms-api:0.2.28-dev  # 0.2.27-dev
          # STABLE SRI WORKING VERSION: image: ghcr.io/biosimulations/sms-api:0.2.15-dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: api-config
          env:
            - name: SLURM_SUBMIT_KEY_PATH
              value: "/run/secrets/slurm_submit_key_file/ssh-privatekey"
            - name: SQLITE_DBPATH
              value: "/app/sqlite/sms-api.db"
          volumeMounts:
            - name: api-sqlite-pvc
              mountPath: /app/sqlite
            - name: api-cache-pvc
              mountPath: /app/scratch
            - name: vivarium-home-pvc
              mountPath: /home/FCAM/svc_vivarium
              subPath: svc_vivarium
            - name: slurm-submit-key-file
              mountPath: /run/secrets/slurm_submit_key_file
            - name: ssh-known-hosts
              mountPath: /run/secrets/ssh-known-hosts
              readOnly: true
      volumes:
        - name: api-sqlite-pvc
          persistentVolumeClaim:
            claimName: api-sqlite-pvc
        - name: api-cache-pvc
          persistentVolumeClaim:
            claimName: api-cache-pvc
        - name: vivarium-home-pvc
          persistentVolumeClaim:
            claimName: vivarium-home-pvc
        - name: slurm-submit-key-file
          secret:
            defaultMode: 256 # 0400
            items:
              - key: ssh-privatekey
                path: ssh-privatekey
            secretName: ssh-secret
        - name: ssh-known-hosts
          configMap:
            name: ssh-known-hosts
      imagePullSecrets:
        - name: ghcr-secret

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    app: api
