apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/biosimulations/sms-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: api-config
          env:
            - name: STORAGE_GCS_CREDENTIALS_FILE
              value: /app/secret/gcs-credentials.json
            - name: MONGODB_URI
              valueFrom:
                  secretKeyRef:
                    name: shared-secrets
                    key: mongodb-uri
          volumeMounts:
            - name: gcs-credentials
              mountPath: /app/secret
              readOnly: true
            - name: api-cache-pvc
              mountPath: /app/scratch
      volumes:
        - name: api-cache-pvc
          persistentVolumeClaim:
            claimName: api-cache-pvc
        - name: gcs-credentials
          secret:
              secretName: shared-secrets
              items:
                - key: gcs_credentials.json
                  path: gcs-credentials.json
      imagePullSecrets:
        - name: ghcr-secret

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    app: api
