---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: sms-api-stanford
spec:
  encryptedData:
    .dockerconfigjson: AgAobZYEnugJ/l6Fae/yd56iSChupxCWQp230ExLcDAiIWU9ifmggdkUrx92vbXhsA2ZE95/dAIDkihZ6s5BZBUYJlzPwudsaC4ogyEGn5JEFBXWu+59tUG0NYLg14PPlYpoZb3ThB217204t8BP9dHbtAoCwGwt/setvehBot3mGahgGbgQYtfLIpHU5E4M8H5u5MxfigbNHza/jWqbgMsRIxkDnelxEmWKALzK9U4mzfJRHdshtH8W7Jd4pUYxywBOWxAHzo6vDU71J+VrSxtm9Yj8VeTlfW2vm6vj4gl2d2L481XQSfDdedYRlrhkkrN1ydBLiVpO2Bd0jmj6115Olm7PPdviJRxWJnATTfRgQTL6g/9FP9IavqEWQW/J9F/hC820y17bFMMQm2NtnLeCdBO0SxxECe206nQFIFO7LjKJB+W2zUf1zAIj0Z9fYjFTlkTtfXnEHyc8kBb9IaHNLyBVlI5Tj9n164c7TEx1dQ10lN8aj5pNHqxFrRjxTp+RiGm844VIGTBkIqd76CH3sh8p9xKxmEBxBWJrQ5fvZ9HKpNCccyWXki9uasq/Iobgu+seLn5l/FiUraDKfKW7W9b+JvXtP7BF559Y3kungm34piwsFCnoraQ/49tI2ZYDjgGAaNgVSSA1elVCPNWfubnQ+FkTQOqSqij9IH5EmFArQCOkqiPj7YRoyHZpCXTRV7dS0SSw8OyQgtJTqlNUD4Mpx/O6X5LHzazteF4lbiSufbTe8uMnmCA1BocNg9p8K1pJnF2FbMs5ALPGX22yUPOXWeVH7tjuYv/KMcz7Ye4/PKbF5N2si0hN1rBCHwlbIFoSiZvBfhz2V8HpHyfHani7fIOiKocrTRNGrZNz/nvWWN3E+ZTWdMvaYzd6EGHQ4KpxBsSP7ODOy4QCngTRxnx14Zf+i4HLiEyKAWQshy+N2Ux9MFOTU6ihqMhk8h6ugM0xLGcvk9NP3ResoaGjWbJwRbQQHQ==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: sms-api-stanford
    type: kubernetes.io/dockerconfigjson
