---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: sms-api-stanford
spec:
  encryptedData:
    .dockerconfigjson: AgDB0W1PPEG3/Y8rG+Fh4ivXenOOE8ORTRIdYvpe04J0pbmb1ywZzhSNmpaYrt5wZhScX9OTYPhJR+h8VgshBIqsQ5+hRXund7TyHrSMk1RBNplkpoKelnlLjAQhfaWBzq5xypqOUePCBIEtMdQ1g7g3TZtr7aO1al5wMIs4lnEoginP+2zX8eN3xGm+3SEYw0WUK+yF/xIlqjRXXZSwhVNhejKUTivt71ZGzPC7v9ZIm6RL16Qu2r/uXNiCUTIvJIBB7/LkJuY3szsHMIQuYCZ/HPtV2gWvmOw2LWdwCsG9aBvKmDZh5oEsvM2mK2NRYmqqWPRxDXxXTE7r9yhLRsacKic25cfaHGMP+Ycwm6VePxcXu+J8GCLguoiHJfgqVrGwzz1MZzoyNJ7TAORx1nlOPNc+F/fIuCBi1I15A/iDqYefmu/571XWbF77rlYsFRNgom668NdAhjruZh0M20y+s66EhAzJ+CXbm3cyah6bLjRCf8nSzyxbHrI1Gam6hoVuY7YxDjOurylaShqb9nzXwEN7CffDrn8lLZrGQMoNjRvuh+KE8gNt+ZfJwhLe0iTvA3LAwRL83LMmlpqwttN4mYmaahjiGRhHBheTkyiay1gnWyhQPEtgEcUSatDLj4tM1TTgOBH2w4W4V8xD4s4OnHPdWSX1O/4bgPbn7iukAJRPWh1h/g4GFhxc5C2K1clYHdFKJiVJai92OQT7oMOWkB4zboj4zCIIjs+QOBeXdzzmk/ise5lGH8WPGUPTj2ijjyuno8IWizfBdjgeZBBelAm5m7+3QDrtaq7qK0nj9ILRWPsHrZF4eFnD2OgT/w++3rG99MAqm6mRtlPadbt5dBsXZN8xaeOmHvl5FNIKkWpIKlJ83jG5S8uvwNHUmLRQidcFzIPmVpX4k2Wbr6o4mYZOPV6iHFYj9cZ84QnB9PHlz3VWwcihXDkk9xAohng7b3l0hpGxep9UMA==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: sms-api-stanford
    type: kubernetes.io/dockerconfigjson
