openapi: 3.1.0
info:
  title: sms-api
  version: 0.2.7
paths:
  /core/simulator/latest:
    get:
      tags:
      - Simulators
      summary: Get the latest simulator version
      operationId: get-latest-simulator
      parameters:
      - name: git_repo_url
        in: query
        required: false
        schema:
          type: string
          default: https://github.com/vivarium-collective/vEcoli
          title: Git Repo Url
      - name: git_branch
        in: query
        required: false
        schema:
          type: string
          default: messages
          title: Git Branch
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Simulator'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /core/simulator/versions:
    get:
      tags:
      - Simulators
      summary: get the list of available simulator versions
      operationId: get-simulator-versions
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisteredSimulators'
  /core/simulator/status:
    get:
      tags:
      - Simulators
      summary: Get simulator container build status by its ID
      operationId: get-simulator-status
      parameters:
      - name: simulator_id
        in: query
        required: true
        schema:
          type: integer
          title: Simulator Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HpcRun'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /core/simulator/upload:
    post:
      tags:
      - Simulators
      summary: Upload a new simulator (vEcoli) version.
      operationId: insert-simulator-version
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Simulator'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimulatorVersion'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /core/simulation/parca:
    post:
      tags:
      - Simulations - Parca
      summary: Run a parameter calculation
      operationId: run-parca
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParcaDatasetRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParcaDataset'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /core/simulation/parca/versions:
    get:
      tags:
      - Simulations - Parca
      summary: Get list of parca calculations
      operationId: get-parca-versions
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ParcaDataset'
                type: array
                title: Response Get-Parca-Versions
  /core/simulation/parca/status:
    get:
      tags:
      - Simulations - Parca
      summary: Get parca calculation status by its ID
      operationId: get-parca-status
      parameters:
      - name: parca_id
        in: query
        required: true
        schema:
          type: integer
          title: Parca Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HpcRun'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /core/simulation/run:
    post:
      tags:
      - Simulations - vEcoli
      summary: Run a vEcoli simulation
      operationId: run-simulation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EcoliSimulationRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EcoliExperiment'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /core/simulation/run/versions:
    get:
      tags:
      - Simulations - vEcoli
      summary: Get list of vEcoli simulations
      operationId: get-simulation-versions
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/EcoliSimulation'
                type: array
                title: Response Get-Simulation-Versions
  /core/simulation/run/status:
    get:
      tags:
      - Simulations - vEcoli
      summary: Get the simulation status record by its ID
      operationId: get-simulation-status
      parameters:
      - name: simulation_id
        in: query
        required: true
        schema:
          type: integer
          title: Simulation Id
      - name: num_events
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          title: Num Events
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HpcRun'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /core/simulation/run/events:
    get:
      tags:
      - Simulations - vEcoli
      summary: Get the worker events for a simulation by its ID
      operationId: get-simulation-worker-events
      parameters:
      - name: simulation_id
        in: query
        required: true
        schema:
          type: integer
          title: Simulation Id
      - name: num_events
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          title: Num Events
      - name: prev_sequence_number
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          title: Prev Sequence Number
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WorkerEvent'
                title: Response Get-Simulation-Worker-Events
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /core/download/analysis:
    get:
      tags:
      - Simulations - vEcoli
      summary: Download a file that was generated from a simulation analysis module
      operationId: download-analysis-file
      parameters:
      - name: experiment_id
        in: query
        required: true
        schema:
          type: string
          description: Experiment ID for the simulation (config.json).
          title: Experiment Id
        description: Experiment ID for the simulation (config.json).
      - name: filename
        in: query
        required: true
        schema:
          type: string
          title: Filename
        example: ptools_rna.txt
      responses:
        '200':
          description: Successful Response
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /:
    get:
      tags:
      - SMS API
      summary: Home
      operationId: home__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /health:
    get:
      tags:
      - SMS API
      summary: Check Health
      operationId: check_health_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
                title: Response Check Health Health Get
  /version:
    get:
      tags:
      - SMS API
      summary: Get Version
      operationId: get_version_version_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: string
                title: Response Get Version Version Get
components:
  schemas:
    AntibioticSimulation:
      properties:
        database_id:
          type: integer
          title: Database Id
        sim_request:
          $ref: '#/components/schemas/AntibioticSimulationRequest'
        slurmjob_id:
          anyOf:
          - type: integer
          - type: 'null'
          title: Slurmjob Id
      type: object
      required:
      - database_id
      - sim_request
      title: AntibioticSimulation
    AntibioticSimulationRequest:
      properties:
        simulator:
          $ref: '#/components/schemas/SimulatorVersion'
        parca_dataset_id:
          type: integer
          title: Parca Dataset Id
        variant_config:
          additionalProperties:
            additionalProperties:
              anyOf:
              - type: integer
              - type: number
              - type: string
            type: object
          type: object
          title: Variant Config
        antibiotics_config:
          additionalProperties:
            additionalProperties:
              anyOf:
              - type: integer
              - type: number
              - type: string
            type: object
          type: object
          title: Antibiotics Config
      type: object
      required:
      - simulator
      - parca_dataset_id
      - variant_config
      title: AntibioticSimulationRequest
    EcoliExperiment:
      properties:
        experiment_id:
          type: string
          title: Experiment Id
        simulation:
          anyOf:
          - $ref: '#/components/schemas/EcoliSimulation'
          - $ref: '#/components/schemas/AntibioticSimulation'
          title: Simulation
        last_updated:
          type: string
          title: Last Updated
        metadata:
          additionalProperties:
            type: string
          type: object
          title: Metadata
      type: object
      required:
      - experiment_id
      - simulation
      title: EcoliExperiment
    EcoliSimulation:
      properties:
        database_id:
          type: integer
          title: Database Id
        sim_request:
          $ref: '#/components/schemas/EcoliSimulationRequest'
        slurmjob_id:
          anyOf:
          - type: integer
          - type: 'null'
          title: Slurmjob Id
      type: object
      required:
      - database_id
      - sim_request
      title: EcoliSimulation
    EcoliSimulationRequest:
      properties:
        simulator:
          $ref: '#/components/schemas/SimulatorVersion'
        parca_dataset_id:
          type: integer
          title: Parca Dataset Id
        variant_config:
          additionalProperties:
            additionalProperties:
              anyOf:
              - type: integer
              - type: number
              - type: string
            type: object
          type: object
          title: Variant Config
      type: object
      required:
      - simulator
      - parca_dataset_id
      - variant_config
      title: EcoliSimulationRequest
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    HpcRun:
      properties:
        database_id:
          type: integer
          title: Database Id
        slurmjobid:
          type: integer
          title: Slurmjobid
        correlation_id:
          type: string
          title: Correlation Id
        job_type:
          $ref: '#/components/schemas/JobType'
        ref_id:
          type: integer
          title: Ref Id
        status:
          anyOf:
          - $ref: '#/components/schemas/JobStatus'
          - type: 'null'
        start_time:
          anyOf:
          - type: string
          - type: 'null'
          title: Start Time
        end_time:
          anyOf:
          - type: string
          - type: 'null'
          title: End Time
        error_message:
          anyOf:
          - type: string
          - type: 'null'
          title: Error Message
      type: object
      required:
      - database_id
      - slurmjobid
      - correlation_id
      - job_type
      - ref_id
      title: HpcRun
    JobStatus:
      type: string
      enum:
      - waiting
      - queued
      - running
      - completed
      - failed
      title: JobStatus
    JobType:
      type: string
      enum:
      - simulation
      - parca
      - build_image
      title: JobType
    ParcaDataset:
      properties:
        database_id:
          type: integer
          title: Database Id
        parca_dataset_request:
          $ref: '#/components/schemas/ParcaDatasetRequest'
        remote_archive_path:
          anyOf:
          - type: string
          - type: 'null'
          title: Remote Archive Path
      type: object
      required:
      - database_id
      - parca_dataset_request
      title: ParcaDataset
    ParcaDatasetRequest:
      properties:
        simulator_version:
          $ref: '#/components/schemas/SimulatorVersion'
        parca_config:
          additionalProperties:
            anyOf:
            - type: integer
            - type: number
            - type: string
          type: object
          title: Parca Config
      type: object
      required:
      - simulator_version
      - parca_config
      title: ParcaDatasetRequest
    RegisteredSimulators:
      properties:
        versions:
          items:
            $ref: '#/components/schemas/SimulatorVersion'
          type: array
          title: Versions
        timestamp:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Timestamp
      type: object
      required:
      - versions
      title: RegisteredSimulators
    Simulator:
      properties:
        git_commit_hash:
          type: string
          title: Git Commit Hash
        git_repo_url:
          type: string
          title: Git Repo Url
        git_branch:
          type: string
          title: Git Branch
      type: object
      required:
      - git_commit_hash
      - git_repo_url
      - git_branch
      title: Simulator
    SimulatorVersion:
      properties:
        git_commit_hash:
          type: string
          title: Git Commit Hash
        git_repo_url:
          type: string
          title: Git Repo Url
        git_branch:
          type: string
          title: Git Branch
        database_id:
          type: integer
          title: Database Id
        created_at:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Created At
      type: object
      required:
      - git_commit_hash
      - git_repo_url
      - git_branch
      - database_id
      title: SimulatorVersion
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    WorkerEvent:
      properties:
        database_id:
          anyOf:
          - type: integer
          - type: 'null'
          title: Database Id
        created_at:
          anyOf:
          - type: string
          - type: 'null'
          title: Created At
        hpcrun_id:
          anyOf:
          - type: integer
          - type: 'null'
          title: Hpcrun Id
        correlation_id:
          type: string
          title: Correlation Id
        sequence_number:
          type: integer
          title: Sequence Number
        mass:
          additionalProperties:
            type: number
          type: object
          title: Mass
        time:
          type: number
          title: Time
      type: object
      required:
      - correlation_id
      - sequence_number
      - mass
      - time
      title: WorkerEvent
