openapi: 3.1.0
info:
  title: sms-api
  version: 0.2.2
servers:
- url: http://localhost:8000
  description: Main Development server
paths:
  /:
    get:
      summary: Root
      operationId: root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
                title: Response Root  Get
  /version:
    get:
      summary: Get Version
      operationId: get_version_version_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: string
                title: Response Get Version Version Get
