---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: sms-api-local
spec:
  encryptedData:
    .dockerconfigjson: AgAwe0hclrDdPUYrleCW5XlDb/ckIK/4IMbAdslSjsucXiX0vktI3OxVFEdeAhA2uw4mqPaOhPR052ZPKL7kQXSUVE75QasiURs6Q3v9zbiJlcOAVsq1stvWWvG+WCNT/7Ba/1TtQe4ERZtg9kEhu6pJ4uByzSeP4DVGGyN2ak/X9Z1OM5O9g2XI9z910NNpZWjBkY43AIo6oF6FQdu0Rs8mN0EaZ0MLKSc8bw0GigkUyY8gLI0xYPqS+nyQU4VK4m1LRRaWUDXsVkxNFya+qkJPxW9OOicGTDFnBoVmhNfRjxSaYfm/BpNaVTjEzEDpnawGg4xQL+vC9MTltZdsdxXt86Gm6+GEGiUm2U9VMdfHlkdjpiwqVYNdOdDM31Nqmit68xsDljyUV3fpxociXjVzGwJtwx9jqxA6sdxlZyg+WpVRNi0gpbRmajGI78QGLEk4s5H+I2r0GrHDn0C2BZUcTbGO7wSF9zHJwwDz7dn5lXcswc6zQNQ7UG+YXWmMUTIk4/tVC5m7a0+y4F9WkcLQO0IYYdR15hrBpAXA3IjrFP22glwjyUH5zpEGoHv4hXRJb5nyzq0Qvvxydr9ZN5wI/w1PhzumLZ+T1x0TRPpasJ001e49XuKDoTnw/bAhoVY92VBj6ffw7Yuod0tXevh5Ikwtplo+9LahT7pF8hqrsI3qlXirYr3fcuxOofBXFKVrxgie/JGc9K59cQz2Rn32ZPGsKIroEwtqkcKjXGGnnecKLVxWZe/Ej0qqAQiStofUTHjvAHklSBIW10Cq7bmOVAedx96Cr9xvH5HiecY4pbWiewRKGr8YIWuRBWZe73RjsRBK71leZUV6BNpm0UkRssZYaJ2+wrt1H5O+y+Uiv3jqzb6ylCo7kNk0d4QDWDsi9FFbPyihNPnPdjSxT0G98ji2tn+za0t2PSiZx7xbU/h8fq4RfAyHx4FhhsLXp/3LMlkU+nRrZbnr3wqSDI9L1rOq8/glGg==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: sms-api-local
    type: kubernetes.io/dockerconfigjson
