name: release-main

on:
  release:
    types: [published]
    branches: [main]

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Build documentation
        run: uv run sphinx-build -b html docs/source docs/_build/html
